services:
  vera:
    build:
      context: .
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
      - 9090:9090
    environment:
      STANDALONE: 1
    volumes:
      - data:/vera
volumes:
  data:
