// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sourcehub/acp/metadata.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/gogoproto/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RelationshipMetadata stores historical data for a Relationship
type RelationshipMetadata struct {
	//tx_hash is the hash of the Tx that created the Relatinoship
	TxHash []byte `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// height at which the relationship was created
	CreationHeight uint64 `protobuf:"varint,2,opt,name=creation_height,json=creationHeight,proto3" json:"creation_height,omitempty"`
	// id of the registration commitment which originally registered the relationship
	RegistrationCommitmentId string `protobuf:"bytes,3,opt,name=registration_commitment_id,json=registrationCommitmentId,proto3" json:"registration_commitment_id,omitempty"`
	// tendermint timestamp for the block which created the Relationship
	CreationHeightTs *types.Timestamp `protobuf:"bytes,4,opt,name=creation_height_ts,json=creationHeightTs,proto3" json:"creation_height_ts,omitempty"`
}

func (m *RelationshipMetadata) Reset()         { *m = RelationshipMetadata{} }
func (m *RelationshipMetadata) String() string { return proto.CompactTextString(m) }
func (*RelationshipMetadata) ProtoMessage()    {}
func (*RelationshipMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b92514a6091ed2b, []int{0}
}
func (m *RelationshipMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelationshipMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelationshipMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelationshipMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationshipMetadata.Merge(m, src)
}
func (m *RelationshipMetadata) XXX_Size() int {
	return m.Size()
}
func (m *RelationshipMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationshipMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RelationshipMetadata proto.InternalMessageInfo

func (m *RelationshipMetadata) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *RelationshipMetadata) GetCreationHeight() uint64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *RelationshipMetadata) GetRegistrationCommitmentId() string {
	if m != nil {
		return m.RegistrationCommitmentId
	}
	return ""
}

func (m *RelationshipMetadata) GetCreationHeightTs() *types.Timestamp {
	if m != nil {
		return m.CreationHeightTs
	}
	return nil
}

func init() {
	proto.RegisterType((*RelationshipMetadata)(nil), "sourcehub.acp.RelationshipMetadata")
}

func init() { proto.RegisterFile("sourcehub/acp/metadata.proto", fileDescriptor_8b92514a6091ed2b) }

var fileDescriptor_8b92514a6091ed2b = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x6b, 0xa8, 0x8a, 0x30, 0x57, 0x59, 0x48, 0x44, 0x15, 0x32, 0x11, 0x0b, 0x99, 0x6c,
	0x09, 0x56, 0x26, 0x58, 0xc2, 0xc0, 0x12, 0x75, 0x62, 0x89, 0x5c, 0xd7, 0xc4, 0x16, 0x75, 0x6d,
	0xd9, 0xa7, 0xa2, 0xbc, 0x05, 0x8f, 0xc5, 0xd8, 0x91, 0xb1, 0x6a, 0x5e, 0x04, 0x91, 0x90, 0x72,
	0x59, 0xcf, 0xf9, 0xec, 0xff, 0xfc, 0x1f, 0x3e, 0x8b, 0x6e, 0x1e, 0xa4, 0xd2, 0xf3, 0x31, 0x17,
	0xd2, 0x73, 0xab, 0x40, 0x4c, 0x04, 0x08, 0xe6, 0x83, 0x03, 0x47, 0x0e, 0x36, 0x5b, 0x26, 0xa4,
	0x1f, 0x9e, 0x57, 0xce, 0x55, 0x53, 0xc5, 0x9b, 0xe5, 0x78, 0xfe, 0xc4, 0xc1, 0x58, 0x15, 0x41,
	0x58, 0xdf, 0xf2, 0x17, 0x2b, 0x84, 0x4f, 0x0a, 0x35, 0x15, 0x60, 0xdc, 0x2c, 0x6a, 0xe3, 0x1f,
	0xbe, 0xbf, 0x23, 0xa7, 0x78, 0x07, 0x16, 0xa5, 0x16, 0x51, 0x27, 0x28, 0x45, 0xd9, 0x7e, 0x31,
	0x80, 0x45, 0x2e, 0xa2, 0x26, 0x97, 0xf8, 0x48, 0x06, 0xd5, 0x3c, 0x28, 0xb5, 0x32, 0x95, 0x86,
	0x64, 0x2b, 0x45, 0x59, 0xbf, 0x38, 0xec, 0xc6, 0x79, 0x33, 0x25, 0x37, 0x78, 0x18, 0x54, 0x65,
	0x22, 0x84, 0x16, 0x96, 0xce, 0x5a, 0x03, 0x56, 0xcd, 0xa0, 0x34, 0x93, 0x64, 0x3b, 0x45, 0xd9,
	0x6e, 0x91, 0xfc, 0x26, 0xee, 0x36, 0xc0, 0xfd, 0x84, 0xe4, 0x98, 0xfc, 0x8b, 0x29, 0x21, 0x26,
	0xfd, 0x14, 0x65, 0x7b, 0x57, 0x43, 0xd6, 0xd6, 0x62, 0x5d, 0x2d, 0x36, 0xea, 0x6a, 0x15, 0xc7,
	0x7f, 0xaf, 0x18, 0xc5, 0xdb, 0xfc, 0x7d, 0x4d, 0xd1, 0x72, 0x4d, 0xd1, 0x6a, 0x4d, 0xd1, 0x5b,
	0x4d, 0x7b, 0xcb, 0x9a, 0xf6, 0x3e, 0x6a, 0xda, 0x7b, 0x64, 0x95, 0x81, 0x2f, 0x53, 0xd2, 0x59,
	0xde, 0x7a, 0x9b, 0x29, 0x78, 0x71, 0xe1, 0x99, 0xff, 0x38, 0x5e, 0x34, 0x96, 0xe1, 0xd5, 0xab,
	0x38, 0x1e, 0x34, 0x79, 0xd7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x48, 0x19, 0xbc, 0x12, 0x83,
	0x01, 0x00, 0x00,
}

func (m *RelationshipMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelationshipMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelationshipMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreationHeightTs != nil {
		{
			size, err := m.CreationHeightTs.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMetadata(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.RegistrationCommitmentId) > 0 {
		i -= len(m.RegistrationCommitmentId)
		copy(dAtA[i:], m.RegistrationCommitmentId)
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.RegistrationCommitmentId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.CreationHeight != 0 {
		i = encodeVarintMetadata(dAtA, i, uint64(m.CreationHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMetadata(dAtA []byte, offset int, v uint64) int {
	offset -= sovMetadata(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RelationshipMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	if m.CreationHeight != 0 {
		n += 1 + sovMetadata(uint64(m.CreationHeight))
	}
	l = len(m.RegistrationCommitmentId)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	if m.CreationHeightTs != nil {
		l = m.CreationHeightTs.Size()
		n += 1 + l + sovMetadata(uint64(l))
	}
	return n
}

func sovMetadata(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMetadata(x uint64) (n int) {
	return sovMetadata(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RelationshipMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelationshipMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelationshipMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = append(m.TxHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TxHash == nil {
				m.TxHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationHeight", wireType)
			}
			m.CreationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationCommitmentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistrationCommitmentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationHeightTs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreationHeightTs == nil {
				m.CreationHeightTs = &types.Timestamp{}
			}
			if err := m.CreationHeightTs.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetadata(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMetadata
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMetadata
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMetadata
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMetadata        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetadata          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMetadata = fmt.Errorf("proto: unexpected end of group")
)
