syntax = "proto3";

package sourcehub.acp;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/sourcenetwork/sourcehub/x/acp/types";

// RegistrationMetadata stores historical data for an Object Registration
message RegistrationMetadata {
    //tx_hash is the hash of the Tx that created the Relatinoship
  bytes tx_hash = 1;

  // height at which the relationship was created
  uint64 creation_height = 2;

  // id of the registration commitment which originally registered the relationship
  string registration_commitment_id = 3;

  // tendermint timestamp for the block which created the Relationship
  google.protobuf.Timestamp creation_height_ts = 4;
}