syntax = "proto3";

package sourcehub.acp;

import "google/protobuf/timestamp.proto";
import "sourcenetwork/acp_core/relationship.proto";

option go_package = "github.com/sourcenetwork/sourcehub/x/acp/types";

enum ObjectRegistrationEventType {
    UNKNOWN = 0;
    REGISTRATION = 1;
    REVEAL_REGISTRATION = 2;
    ARCHIVAL = 3;
    UNARCHIVAL = 4;
    AMENDMENT = 5;
    TRANSFER = 6;
}

message ObjectRegistrationEvent {
    string id = 1;
    ObjectRegistrationEventType type = 2;
    bytes tx_hash = 3;
    uint64 height = 4;
    google.protobuf.Timestamp ts = 5;
    string policy_id = 6;
    sourcenetwork.acp_core.Object object = 7;
    sourcenetwork.acp_core.Actor actor = 8;
    EventDetail detail = 9;
}

message EventDetail {
    oneof detail {
        RevealRegistrationDetail reveal_event = 2;
        AmendmentEventDetail amendment_event = 3;
    }
}

message AmendmentEventDetail {
    bool hijack_flag = 1;
    sourcenetwork.acp_core.Actor previous_owner = 2;
    string reveal_registration_event_id = 3;

    uint64 commitment_creation_height = 4;
}

message RevealRegistrationDetail {
    uint64 commitment_creation_height = 1;

    // id of the registration commitment which originally registered the relationship
    string registration_commitment_id = 2;
}