// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vera/orbis/events.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventRingCreated is emitted when a ring is created.
type EventRingCreated struct {
	RingId     string `protobuf:"bytes,1,opt,name=ring_id,json=ringId,proto3" json:"ring_id,omitempty"`
	CreatorDid string `protobuf:"bytes,2,opt,name=creator_did,json=creatorDid,proto3" json:"creator_did,omitempty"`
}

func (m *EventRingCreated) Reset()         { *m = EventRingCreated{} }
func (m *EventRingCreated) String() string { return proto.CompactTextString(m) }
func (*EventRingCreated) ProtoMessage()    {}
func (*EventRingCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{0}
}
func (m *EventRingCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRingCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRingCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRingCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRingCreated.Merge(m, src)
}
func (m *EventRingCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventRingCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRingCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventRingCreated proto.InternalMessageInfo

func (m *EventRingCreated) GetRingId() string {
	if m != nil {
		return m.RingId
	}
	return ""
}

func (m *EventRingCreated) GetCreatorDid() string {
	if m != nil {
		return m.CreatorDid
	}
	return ""
}

// EventRingUpdated is emitted when a ring is updated in place.
type EventRingUpdated struct {
	RingId     string `protobuf:"bytes,1,opt,name=ring_id,json=ringId,proto3" json:"ring_id,omitempty"`
	UpdaterDid string `protobuf:"bytes,2,opt,name=updater_did,json=updaterDid,proto3" json:"updater_did,omitempty"`
}

func (m *EventRingUpdated) Reset()         { *m = EventRingUpdated{} }
func (m *EventRingUpdated) String() string { return proto.CompactTextString(m) }
func (*EventRingUpdated) ProtoMessage()    {}
func (*EventRingUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{1}
}
func (m *EventRingUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRingUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRingUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRingUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRingUpdated.Merge(m, src)
}
func (m *EventRingUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EventRingUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRingUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventRingUpdated proto.InternalMessageInfo

func (m *EventRingUpdated) GetRingId() string {
	if m != nil {
		return m.RingId
	}
	return ""
}

func (m *EventRingUpdated) GetUpdaterDid() string {
	if m != nil {
		return m.UpdaterDid
	}
	return ""
}

// EventDocumentStored is emitted when an encrypted document is stored.
type EventDocumentStored struct {
	DocumentId string `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	CreatorDid string `protobuf:"bytes,2,opt,name=creator_did,json=creatorDid,proto3" json:"creator_did,omitempty"`
}

func (m *EventDocumentStored) Reset()         { *m = EventDocumentStored{} }
func (m *EventDocumentStored) String() string { return proto.CompactTextString(m) }
func (*EventDocumentStored) ProtoMessage()    {}
func (*EventDocumentStored) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{2}
}
func (m *EventDocumentStored) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDocumentStored) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDocumentStored.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDocumentStored) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDocumentStored.Merge(m, src)
}
func (m *EventDocumentStored) XXX_Size() int {
	return m.Size()
}
func (m *EventDocumentStored) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDocumentStored.DiscardUnknown(m)
}

var xxx_messageInfo_EventDocumentStored proto.InternalMessageInfo

func (m *EventDocumentStored) GetDocumentId() string {
	if m != nil {
		return m.DocumentId
	}
	return ""
}

func (m *EventDocumentStored) GetCreatorDid() string {
	if m != nil {
		return m.CreatorDid
	}
	return ""
}

// EventKeyDerivationStored is emitted when a key derivation is stored.
type EventKeyDerivationStored struct {
	KeyDerivationId string `protobuf:"bytes,1,opt,name=key_derivation_id,json=keyDerivationId,proto3" json:"key_derivation_id,omitempty"`
	CreatorDid      string `protobuf:"bytes,2,opt,name=creator_did,json=creatorDid,proto3" json:"creator_did,omitempty"`
}

func (m *EventKeyDerivationStored) Reset()         { *m = EventKeyDerivationStored{} }
func (m *EventKeyDerivationStored) String() string { return proto.CompactTextString(m) }
func (*EventKeyDerivationStored) ProtoMessage()    {}
func (*EventKeyDerivationStored) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{3}
}
func (m *EventKeyDerivationStored) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventKeyDerivationStored) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventKeyDerivationStored.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventKeyDerivationStored) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventKeyDerivationStored.Merge(m, src)
}
func (m *EventKeyDerivationStored) XXX_Size() int {
	return m.Size()
}
func (m *EventKeyDerivationStored) XXX_DiscardUnknown() {
	xxx_messageInfo_EventKeyDerivationStored.DiscardUnknown(m)
}

var xxx_messageInfo_EventKeyDerivationStored proto.InternalMessageInfo

func (m *EventKeyDerivationStored) GetKeyDerivationId() string {
	if m != nil {
		return m.KeyDerivationId
	}
	return ""
}

func (m *EventKeyDerivationStored) GetCreatorDid() string {
	if m != nil {
		return m.CreatorDid
	}
	return ""
}

// EventNodeInfoCreated is emitted when a node info record is created.
type EventNodeInfoCreated struct {
	PeerId        string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ControllerKey string `protobuf:"bytes,2,opt,name=controller_key,json=controllerKey,proto3" json:"controller_key,omitempty"`
}

func (m *EventNodeInfoCreated) Reset()         { *m = EventNodeInfoCreated{} }
func (m *EventNodeInfoCreated) String() string { return proto.CompactTextString(m) }
func (*EventNodeInfoCreated) ProtoMessage()    {}
func (*EventNodeInfoCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{4}
}
func (m *EventNodeInfoCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventNodeInfoCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventNodeInfoCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventNodeInfoCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventNodeInfoCreated.Merge(m, src)
}
func (m *EventNodeInfoCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventNodeInfoCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventNodeInfoCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventNodeInfoCreated proto.InternalMessageInfo

func (m *EventNodeInfoCreated) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *EventNodeInfoCreated) GetControllerKey() string {
	if m != nil {
		return m.ControllerKey
	}
	return ""
}

// EventNodeInfoUpdated is emitted when a node info record is updated.
type EventNodeInfoUpdated struct {
	PeerId        string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	ControllerKey string `protobuf:"bytes,2,opt,name=controller_key,json=controllerKey,proto3" json:"controller_key,omitempty"`
}

func (m *EventNodeInfoUpdated) Reset()         { *m = EventNodeInfoUpdated{} }
func (m *EventNodeInfoUpdated) String() string { return proto.CompactTextString(m) }
func (*EventNodeInfoUpdated) ProtoMessage()    {}
func (*EventNodeInfoUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{5}
}
func (m *EventNodeInfoUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventNodeInfoUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventNodeInfoUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventNodeInfoUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventNodeInfoUpdated.Merge(m, src)
}
func (m *EventNodeInfoUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EventNodeInfoUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventNodeInfoUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventNodeInfoUpdated proto.InternalMessageInfo

func (m *EventNodeInfoUpdated) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *EventNodeInfoUpdated) GetControllerKey() string {
	if m != nil {
		return m.ControllerKey
	}
	return ""
}

// EventRingDeleted is emitted when a ring is removed from state.
type EventRingDeleted struct {
	RingId string `protobuf:"bytes,1,opt,name=ring_id,json=ringId,proto3" json:"ring_id,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *EventRingDeleted) Reset()         { *m = EventRingDeleted{} }
func (m *EventRingDeleted) String() string { return proto.CompactTextString(m) }
func (*EventRingDeleted) ProtoMessage()    {}
func (*EventRingDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{6}
}
func (m *EventRingDeleted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRingDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRingDeleted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRingDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRingDeleted.Merge(m, src)
}
func (m *EventRingDeleted) XXX_Size() int {
	return m.Size()
}
func (m *EventRingDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRingDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_EventRingDeleted proto.InternalMessageInfo

func (m *EventRingDeleted) GetRingId() string {
	if m != nil {
		return m.RingId
	}
	return ""
}

func (m *EventRingDeleted) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// EventRingUpgradeScheduled is emitted when a future ring upgrade is scheduled.
type EventRingUpgradeScheduled struct {
	RingId         string `protobuf:"bytes,1,opt,name=ring_id,json=ringId,proto3" json:"ring_id,omitempty"`
	CurrentVersion uint64 `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	NextVersion    uint64 `protobuf:"varint,3,opt,name=next_version,json=nextVersion,proto3" json:"next_version,omitempty"`
	ActivationTime uint64 `protobuf:"varint,4,opt,name=activation_time,json=activationTime,proto3" json:"activation_time,omitempty"`
}

func (m *EventRingUpgradeScheduled) Reset()         { *m = EventRingUpgradeScheduled{} }
func (m *EventRingUpgradeScheduled) String() string { return proto.CompactTextString(m) }
func (*EventRingUpgradeScheduled) ProtoMessage()    {}
func (*EventRingUpgradeScheduled) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{7}
}
func (m *EventRingUpgradeScheduled) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRingUpgradeScheduled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRingUpgradeScheduled.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRingUpgradeScheduled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRingUpgradeScheduled.Merge(m, src)
}
func (m *EventRingUpgradeScheduled) XXX_Size() int {
	return m.Size()
}
func (m *EventRingUpgradeScheduled) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRingUpgradeScheduled.DiscardUnknown(m)
}

var xxx_messageInfo_EventRingUpgradeScheduled proto.InternalMessageInfo

func (m *EventRingUpgradeScheduled) GetRingId() string {
	if m != nil {
		return m.RingId
	}
	return ""
}

func (m *EventRingUpgradeScheduled) GetCurrentVersion() uint64 {
	if m != nil {
		return m.CurrentVersion
	}
	return 0
}

func (m *EventRingUpgradeScheduled) GetNextVersion() uint64 {
	if m != nil {
		return m.NextVersion
	}
	return 0
}

func (m *EventRingUpgradeScheduled) GetActivationTime() uint64 {
	if m != nil {
		return m.ActivationTime
	}
	return 0
}

// EventRingUpgradeCancelled is emitted when a pending ring upgrade is cancelled.
type EventRingUpgradeCancelled struct {
	RingId         string `protobuf:"bytes,1,opt,name=ring_id,json=ringId,proto3" json:"ring_id,omitempty"`
	CurrentVersion uint64 `protobuf:"varint,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
}

func (m *EventRingUpgradeCancelled) Reset()         { *m = EventRingUpgradeCancelled{} }
func (m *EventRingUpgradeCancelled) String() string { return proto.CompactTextString(m) }
func (*EventRingUpgradeCancelled) ProtoMessage()    {}
func (*EventRingUpgradeCancelled) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{8}
}
func (m *EventRingUpgradeCancelled) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRingUpgradeCancelled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRingUpgradeCancelled.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRingUpgradeCancelled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRingUpgradeCancelled.Merge(m, src)
}
func (m *EventRingUpgradeCancelled) XXX_Size() int {
	return m.Size()
}
func (m *EventRingUpgradeCancelled) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRingUpgradeCancelled.DiscardUnknown(m)
}

var xxx_messageInfo_EventRingUpgradeCancelled proto.InternalMessageInfo

func (m *EventRingUpgradeCancelled) GetRingId() string {
	if m != nil {
		return m.RingId
	}
	return ""
}

func (m *EventRingUpgradeCancelled) GetCurrentVersion() uint64 {
	if m != nil {
		return m.CurrentVersion
	}
	return 0
}

// EventRingUpgradeNormalized is emitted when a scheduled upgrade becomes active.
type EventRingUpgradeNormalized struct {
	RingId          string `protobuf:"bytes,1,opt,name=ring_id,json=ringId,proto3" json:"ring_id,omitempty"`
	PreviousVersion uint64 `protobuf:"varint,2,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty"`
	CurrentVersion  uint64 `protobuf:"varint,3,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	ActivationTime  uint64 `protobuf:"varint,4,opt,name=activation_time,json=activationTime,proto3" json:"activation_time,omitempty"`
}

func (m *EventRingUpgradeNormalized) Reset()         { *m = EventRingUpgradeNormalized{} }
func (m *EventRingUpgradeNormalized) String() string { return proto.CompactTextString(m) }
func (*EventRingUpgradeNormalized) ProtoMessage()    {}
func (*EventRingUpgradeNormalized) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{9}
}
func (m *EventRingUpgradeNormalized) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRingUpgradeNormalized) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRingUpgradeNormalized.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRingUpgradeNormalized) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRingUpgradeNormalized.Merge(m, src)
}
func (m *EventRingUpgradeNormalized) XXX_Size() int {
	return m.Size()
}
func (m *EventRingUpgradeNormalized) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRingUpgradeNormalized.DiscardUnknown(m)
}

var xxx_messageInfo_EventRingUpgradeNormalized proto.InternalMessageInfo

func (m *EventRingUpgradeNormalized) GetRingId() string {
	if m != nil {
		return m.RingId
	}
	return ""
}

func (m *EventRingUpgradeNormalized) GetPreviousVersion() uint64 {
	if m != nil {
		return m.PreviousVersion
	}
	return 0
}

func (m *EventRingUpgradeNormalized) GetCurrentVersion() uint64 {
	if m != nil {
		return m.CurrentVersion
	}
	return 0
}

func (m *EventRingUpgradeNormalized) GetActivationTime() uint64 {
	if m != nil {
		return m.ActivationTime
	}
	return 0
}

// EventReportAccepted is emitted after an MPC fault report passes security validation.
type EventReportAccepted struct {
	ReportId        string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	RingId          string `protobuf:"bytes,2,opt,name=ring_id,json=ringId,proto3" json:"ring_id,omitempty"`
	ReportType      string `protobuf:"bytes,3,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"`
	ReporterNodeKey string `protobuf:"bytes,4,opt,name=reporter_node_key,json=reporterNodeKey,proto3" json:"reporter_node_key,omitempty"`
	AccusedNodeKey  string `protobuf:"bytes,5,opt,name=accused_node_key,json=accusedNodeKey,proto3" json:"accused_node_key,omitempty"`
}

func (m *EventReportAccepted) Reset()         { *m = EventReportAccepted{} }
func (m *EventReportAccepted) String() string { return proto.CompactTextString(m) }
func (*EventReportAccepted) ProtoMessage()    {}
func (*EventReportAccepted) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{10}
}
func (m *EventReportAccepted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventReportAccepted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventReportAccepted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventReportAccepted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReportAccepted.Merge(m, src)
}
func (m *EventReportAccepted) XXX_Size() int {
	return m.Size()
}
func (m *EventReportAccepted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReportAccepted.DiscardUnknown(m)
}

var xxx_messageInfo_EventReportAccepted proto.InternalMessageInfo

func (m *EventReportAccepted) GetReportId() string {
	if m != nil {
		return m.ReportId
	}
	return ""
}

func (m *EventReportAccepted) GetRingId() string {
	if m != nil {
		return m.RingId
	}
	return ""
}

func (m *EventReportAccepted) GetReportType() string {
	if m != nil {
		return m.ReportType
	}
	return ""
}

func (m *EventReportAccepted) GetReporterNodeKey() string {
	if m != nil {
		return m.ReporterNodeKey
	}
	return ""
}

func (m *EventReportAccepted) GetAccusedNodeKey() string {
	if m != nil {
		return m.AccusedNodeKey
	}
	return ""
}

// EventRingAutoReshareScheduled is emitted when accepted reports trigger a replacement reshare.
type EventRingAutoReshareScheduled struct {
	RingId             string `protobuf:"bytes,1,opt,name=ring_id,json=ringId,proto3" json:"ring_id,omitempty"`
	AccusedNodeKey     string `protobuf:"bytes,2,opt,name=accused_node_key,json=accusedNodeKey,proto3" json:"accused_node_key,omitempty"`
	ReplacementNodeKey string `protobuf:"bytes,3,opt,name=replacement_node_key,json=replacementNodeKey,proto3" json:"replacement_node_key,omitempty"`
	KickThreshold      uint64 `protobuf:"varint,4,opt,name=kick_threshold,json=kickThreshold,proto3" json:"kick_threshold,omitempty"`
	Demerits           uint64 `protobuf:"varint,5,opt,name=demerits,proto3" json:"demerits,omitempty"`
}

func (m *EventRingAutoReshareScheduled) Reset()         { *m = EventRingAutoReshareScheduled{} }
func (m *EventRingAutoReshareScheduled) String() string { return proto.CompactTextString(m) }
func (*EventRingAutoReshareScheduled) ProtoMessage()    {}
func (*EventRingAutoReshareScheduled) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{11}
}
func (m *EventRingAutoReshareScheduled) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRingAutoReshareScheduled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRingAutoReshareScheduled.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRingAutoReshareScheduled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRingAutoReshareScheduled.Merge(m, src)
}
func (m *EventRingAutoReshareScheduled) XXX_Size() int {
	return m.Size()
}
func (m *EventRingAutoReshareScheduled) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRingAutoReshareScheduled.DiscardUnknown(m)
}

var xxx_messageInfo_EventRingAutoReshareScheduled proto.InternalMessageInfo

func (m *EventRingAutoReshareScheduled) GetRingId() string {
	if m != nil {
		return m.RingId
	}
	return ""
}

func (m *EventRingAutoReshareScheduled) GetAccusedNodeKey() string {
	if m != nil {
		return m.AccusedNodeKey
	}
	return ""
}

func (m *EventRingAutoReshareScheduled) GetReplacementNodeKey() string {
	if m != nil {
		return m.ReplacementNodeKey
	}
	return ""
}

func (m *EventRingAutoReshareScheduled) GetKickThreshold() uint64 {
	if m != nil {
		return m.KickThreshold
	}
	return 0
}

func (m *EventRingAutoReshareScheduled) GetDemerits() uint64 {
	if m != nil {
		return m.Demerits
	}
	return 0
}

// EventNodeKeyDrained is emitted when a node key's balance is drained to its controller.
type EventNodeKeyDrained struct {
	NodeKey   string       `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	Recipient string       `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount    []types.Coin `protobuf:"bytes,3,rep,name=amount,proto3" json:"amount"`
}

func (m *EventNodeKeyDrained) Reset()         { *m = EventNodeKeyDrained{} }
func (m *EventNodeKeyDrained) String() string { return proto.CompactTextString(m) }
func (*EventNodeKeyDrained) ProtoMessage()    {}
func (*EventNodeKeyDrained) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e03870efdf23dd7, []int{12}
}
func (m *EventNodeKeyDrained) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventNodeKeyDrained) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventNodeKeyDrained.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventNodeKeyDrained) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventNodeKeyDrained.Merge(m, src)
}
func (m *EventNodeKeyDrained) XXX_Size() int {
	return m.Size()
}
func (m *EventNodeKeyDrained) XXX_DiscardUnknown() {
	xxx_messageInfo_EventNodeKeyDrained.DiscardUnknown(m)
}

var xxx_messageInfo_EventNodeKeyDrained proto.InternalMessageInfo

func (m *EventNodeKeyDrained) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *EventNodeKeyDrained) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *EventNodeKeyDrained) GetAmount() []types.Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

func init() {
	proto.RegisterType((*EventRingCreated)(nil), "vera.orbis.EventRingCreated")
	proto.RegisterType((*EventRingUpdated)(nil), "vera.orbis.EventRingUpdated")
	proto.RegisterType((*EventDocumentStored)(nil), "vera.orbis.EventDocumentStored")
	proto.RegisterType((*EventKeyDerivationStored)(nil), "vera.orbis.EventKeyDerivationStored")
	proto.RegisterType((*EventNodeInfoCreated)(nil), "vera.orbis.EventNodeInfoCreated")
	proto.RegisterType((*EventNodeInfoUpdated)(nil), "vera.orbis.EventNodeInfoUpdated")
	proto.RegisterType((*EventRingDeleted)(nil), "vera.orbis.EventRingDeleted")
	proto.RegisterType((*EventRingUpgradeScheduled)(nil), "vera.orbis.EventRingUpgradeScheduled")
	proto.RegisterType((*EventRingUpgradeCancelled)(nil), "vera.orbis.EventRingUpgradeCancelled")
	proto.RegisterType((*EventRingUpgradeNormalized)(nil), "vera.orbis.EventRingUpgradeNormalized")
	proto.RegisterType((*EventReportAccepted)(nil), "vera.orbis.EventReportAccepted")
	proto.RegisterType((*EventRingAutoReshareScheduled)(nil), "vera.orbis.EventRingAutoReshareScheduled")
	proto.RegisterType((*EventNodeKeyDrained)(nil), "vera.orbis.EventNodeKeyDrained")
}

func init() { proto.RegisterFile("vera/orbis/events.proto", fileDescriptor_6e03870efdf23dd7) }

var fileDescriptor_6e03870efdf23dd7 = []byte{
	// 741 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcf, 0x4e, 0xdb, 0x48,
	0x18, 0x8f, 0x49, 0x36, 0xc0, 0xb0, 0x24, 0xac, 0x17, 0x2d, 0x21, 0xbb, 0x1b, 0xd8, 0x48, 0x08,
	0x76, 0x57, 0x8a, 0x97, 0xed, 0xa1, 0x67, 0x48, 0x38, 0x44, 0x54, 0x1c, 0x0c, 0xa5, 0x52, 0xa5,
	0x2a, 0x72, 0x66, 0xbe, 0x26, 0xa3, 0xd8, 0x33, 0xd6, 0x78, 0x9c, 0x92, 0xbe, 0x40, 0xaf, 0x7d,
	0x8d, 0x5e, 0xfb, 0x08, 0x3d, 0x71, 0xe4, 0xd6, 0x9e, 0xaa, 0x0a, 0x5e, 0xa4, 0x9a, 0xf1, 0x38,
	0x36, 0x01, 0xd1, 0x48, 0xed, 0xcd, 0xf3, 0xfb, 0x7e, 0xf3, 0xfb, 0xfe, 0x8e, 0x3f, 0xb4, 0x31,
	0x06, 0xe1, 0x39, 0x5c, 0xf4, 0x69, 0xe4, 0xc0, 0x18, 0x98, 0x8c, 0x5a, 0xa1, 0xe0, 0x92, 0xdb,
	0x48, 0x19, 0x5a, 0xda, 0x50, 0x6f, 0x60, 0x1e, 0x05, 0x3c, 0x72, 0xfa, 0x5e, 0x04, 0xce, 0x78,
	0xbf, 0x0f, 0xd2, 0xdb, 0x77, 0x30, 0xa7, 0x2c, 0xe1, 0xd6, 0xd7, 0x07, 0x7c, 0xc0, 0xf5, 0xa7,
	0xa3, 0xbe, 0x12, 0xb4, 0xf9, 0x04, 0xad, 0x1d, 0x29, 0x45, 0x97, 0xb2, 0x41, 0x5b, 0x80, 0x27,
	0x81, 0xd8, 0x1b, 0x68, 0x51, 0x50, 0x36, 0xe8, 0x51, 0x52, 0xb3, 0xb6, 0xad, 0xbd, 0x65, 0xb7,
	0xac, 0x8e, 0x5d, 0x62, 0x6f, 0xa1, 0x15, 0xac, 0x38, 0x5c, 0xf4, 0x08, 0x25, 0xb5, 0x05, 0x6d,
	0x44, 0x06, 0xea, 0x50, 0x72, 0x4b, 0xed, 0x69, 0x48, 0xbe, 0xa9, 0x16, 0x6b, 0xce, 0x2d, 0x35,
	0x03, 0x29, 0xb5, 0x67, 0xe8, 0x57, 0xad, 0xd6, 0xe1, 0x38, 0x0e, 0x80, 0xc9, 0x53, 0xc9, 0x05,
	0xe8, 0x7b, 0xc4, 0x20, 0x99, 0x28, 0x4a, 0xa1, 0x79, 0xc2, 0x1c, 0xa0, 0x9a, 0x16, 0x3e, 0x86,
	0x49, 0x07, 0x04, 0x1d, 0x7b, 0x92, 0x72, 0x66, 0xd4, 0xff, 0x41, 0xbf, 0x8c, 0x60, 0xd2, 0x23,
	0x53, 0x3c, 0xf3, 0x51, 0x1d, 0xe5, 0xf9, 0xf3, 0x38, 0x3a, 0x47, 0xeb, 0xda, 0xd1, 0x09, 0x27,
	0xd0, 0x65, 0x2f, 0x79, 0xae, 0xc2, 0x21, 0x80, 0xc8, 0xd5, 0x44, 0x1d, 0xbb, 0xc4, 0xde, 0x41,
	0x15, 0xcc, 0x99, 0x14, 0xdc, 0xf7, 0x41, 0xf4, 0x46, 0x30, 0x31, 0xa2, 0xab, 0x19, 0x7a, 0x0c,
	0x93, 0x3b, 0xba, 0xb9, 0x5a, 0x7f, 0x97, 0x6e, 0x3b, 0xd7, 0xbf, 0x0e, 0xf8, 0xf0, 0x60, 0xff,
	0x7e, 0x43, 0x65, 0x01, 0x5e, 0xc4, 0x99, 0xd1, 0x32, 0xa7, 0xe6, 0x3b, 0x0b, 0x6d, 0xe6, 0xa6,
	0x60, 0x20, 0x3c, 0x02, 0xa7, 0x78, 0x08, 0x24, 0xf6, 0x1f, 0x92, 0xdb, 0x45, 0x55, 0x1c, 0x0b,
	0xa1, 0xba, 0x3a, 0x06, 0x11, 0x51, 0xa3, 0x5b, 0x72, 0x2b, 0x06, 0x3e, 0x4f, 0x50, 0xfb, 0x2f,
	0xf4, 0x33, 0x83, 0x8b, 0x8c, 0x55, 0xd4, 0xac, 0x15, 0x85, 0xa5, 0x94, 0x5d, 0x54, 0xf5, 0xb0,
	0x4c, 0x1b, 0x28, 0x69, 0x00, 0xb5, 0x52, 0xa2, 0x95, 0xc1, 0x67, 0x34, 0x80, 0xe6, 0x8b, 0xbb,
	0xa1, 0xb6, 0x3d, 0x86, 0xc1, 0xff, 0x21, 0xa1, 0x36, 0xdf, 0x5b, 0xa8, 0x3e, 0xab, 0x7f, 0xc2,
	0x45, 0xe0, 0xf9, 0xf4, 0xf5, 0x43, 0x0e, 0xfe, 0x46, 0x6b, 0xa1, 0x80, 0x31, 0xe5, 0x71, 0x34,
	0xe3, 0xa1, 0x9a, 0xe2, 0xb9, 0x54, 0x67, 0x63, 0x29, 0xde, 0x5b, 0xb6, 0xb9, 0x6b, 0xf2, 0xc1,
	0x32, 0xef, 0xce, 0x85, 0x90, 0x0b, 0x79, 0x80, 0x31, 0x84, 0x6a, 0x10, 0x7e, 0x47, 0xcb, 0x42,
	0x23, 0x59, 0xbc, 0x4b, 0x09, 0xd0, 0xbd, 0x95, 0xca, 0xc2, 0xec, 0x2b, 0x37, 0xb7, 0xe4, 0x24,
	0x04, 0x1d, 0xdb, 0xb2, 0x8b, 0x12, 0xe8, 0x6c, 0x12, 0x82, 0x7a, 0x70, 0xc9, 0x09, 0x44, 0x8f,
	0x71, 0x02, 0x7a, 0x3a, 0x4b, 0xc9, 0x83, 0x4b, 0x0d, 0x6a, 0xce, 0x8f, 0x61, 0x62, 0xef, 0xa1,
	0x35, 0x0f, 0xe3, 0x38, 0x02, 0x92, 0x51, 0x7f, 0xd2, 0xd4, 0x8a, 0xc1, 0x0d, 0xb3, 0xf9, 0xd1,
	0x42, 0x7f, 0x4e, 0x2b, 0x7f, 0x10, 0x4b, 0xee, 0x42, 0x34, 0xf4, 0xc4, 0x3c, 0x83, 0x78, 0x9f,
	0x93, 0x85, 0xfb, 0x9c, 0xd8, 0xff, 0xa1, 0x75, 0x01, 0xa1, 0xef, 0x61, 0xd0, 0x3f, 0xa3, 0x29,
	0x3b, 0x49, 0xd2, 0xce, 0xd9, 0xd2, 0x1b, 0x3b, 0xa8, 0x32, 0xa2, 0x78, 0xd4, 0x93, 0x43, 0x01,
	0xd1, 0x90, 0xfb, 0xc4, 0xf4, 0x60, 0x55, 0xa1, 0x67, 0x29, 0x68, 0xd7, 0xd1, 0x12, 0x81, 0x00,
	0x04, 0x95, 0x91, 0xce, 0xaf, 0xe4, 0x4e, 0xcf, 0xcd, 0x37, 0x69, 0x7b, 0x8c, 0x66, 0x47, 0x78,
	0x94, 0x01, 0xb1, 0x37, 0xd1, 0xd2, 0x34, 0x80, 0x24, 0xa1, 0x45, 0x66, 0xbc, 0xfe, 0xa1, 0x3a,
	0x87, 0x69, 0x48, 0x81, 0x49, 0x93, 0x4a, 0x06, 0xd8, 0x8f, 0x51, 0xd9, 0x0b, 0x78, 0xcc, 0x64,
	0xad, 0xb8, 0x5d, 0xdc, 0x5b, 0xf9, 0x7f, 0xb3, 0x95, 0x6c, 0x92, 0x96, 0xda, 0x24, 0x2d, 0xb3,
	0x49, 0x5a, 0x6d, 0x4e, 0xd9, 0x61, 0xe9, 0xf2, 0xf3, 0x56, 0xc1, 0x35, 0xf4, 0xc3, 0xa3, 0xcb,
	0xeb, 0x86, 0x75, 0x75, 0xdd, 0xb0, 0xbe, 0x5c, 0x37, 0xac, 0xb7, 0x37, 0x8d, 0xc2, 0xd5, 0x4d,
	0xa3, 0xf0, 0xe9, 0xa6, 0x51, 0x78, 0xfe, 0xef, 0x80, 0xca, 0x61, 0xdc, 0x6f, 0x61, 0x1e, 0x38,
	0x11, 0x8f, 0x05, 0x06, 0x06, 0xf2, 0x15, 0x17, 0x23, 0x47, 0x6f, 0xb2, 0x0b, 0xb3, 0xcb, 0xd4,
	0x44, 0x44, 0xfd, 0xb2, 0xde, 0x44, 0x8f, 0xbe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x82, 0x5c,
	0xed, 0xe6, 0x06, 0x00, 0x00,
}

func (m *EventRingCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRingCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRingCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CreatorDid) > 0 {
		i -= len(m.CreatorDid)
		copy(dAtA[i:], m.CreatorDid)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.CreatorDid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RingId) > 0 {
		i -= len(m.RingId)
		copy(dAtA[i:], m.RingId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RingId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRingUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRingUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRingUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpdaterDid) > 0 {
		i -= len(m.UpdaterDid)
		copy(dAtA[i:], m.UpdaterDid)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.UpdaterDid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RingId) > 0 {
		i -= len(m.RingId)
		copy(dAtA[i:], m.RingId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RingId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventDocumentStored) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDocumentStored) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDocumentStored) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CreatorDid) > 0 {
		i -= len(m.CreatorDid)
		copy(dAtA[i:], m.CreatorDid)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.CreatorDid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DocumentId) > 0 {
		i -= len(m.DocumentId)
		copy(dAtA[i:], m.DocumentId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.DocumentId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventKeyDerivationStored) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventKeyDerivationStored) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventKeyDerivationStored) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CreatorDid) > 0 {
		i -= len(m.CreatorDid)
		copy(dAtA[i:], m.CreatorDid)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.CreatorDid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.KeyDerivationId) > 0 {
		i -= len(m.KeyDerivationId)
		copy(dAtA[i:], m.KeyDerivationId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.KeyDerivationId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventNodeInfoCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventNodeInfoCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventNodeInfoCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ControllerKey) > 0 {
		i -= len(m.ControllerKey)
		copy(dAtA[i:], m.ControllerKey)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ControllerKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PeerId) > 0 {
		i -= len(m.PeerId)
		copy(dAtA[i:], m.PeerId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.PeerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventNodeInfoUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventNodeInfoUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventNodeInfoUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ControllerKey) > 0 {
		i -= len(m.ControllerKey)
		copy(dAtA[i:], m.ControllerKey)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ControllerKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PeerId) > 0 {
		i -= len(m.PeerId)
		copy(dAtA[i:], m.PeerId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.PeerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRingDeleted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRingDeleted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRingDeleted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RingId) > 0 {
		i -= len(m.RingId)
		copy(dAtA[i:], m.RingId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RingId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRingUpgradeScheduled) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRingUpgradeScheduled) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRingUpgradeScheduled) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActivationTime != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.ActivationTime))
		i--
		dAtA[i] = 0x20
	}
	if m.NextVersion != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.NextVersion))
		i--
		dAtA[i] = 0x18
	}
	if m.CurrentVersion != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.CurrentVersion))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RingId) > 0 {
		i -= len(m.RingId)
		copy(dAtA[i:], m.RingId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RingId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRingUpgradeCancelled) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRingUpgradeCancelled) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRingUpgradeCancelled) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentVersion != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.CurrentVersion))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RingId) > 0 {
		i -= len(m.RingId)
		copy(dAtA[i:], m.RingId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RingId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRingUpgradeNormalized) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRingUpgradeNormalized) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRingUpgradeNormalized) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ActivationTime != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.ActivationTime))
		i--
		dAtA[i] = 0x20
	}
	if m.CurrentVersion != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.CurrentVersion))
		i--
		dAtA[i] = 0x18
	}
	if m.PreviousVersion != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.PreviousVersion))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RingId) > 0 {
		i -= len(m.RingId)
		copy(dAtA[i:], m.RingId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RingId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventReportAccepted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventReportAccepted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventReportAccepted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccusedNodeKey) > 0 {
		i -= len(m.AccusedNodeKey)
		copy(dAtA[i:], m.AccusedNodeKey)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.AccusedNodeKey)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ReporterNodeKey) > 0 {
		i -= len(m.ReporterNodeKey)
		copy(dAtA[i:], m.ReporterNodeKey)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ReporterNodeKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ReportType) > 0 {
		i -= len(m.ReportType)
		copy(dAtA[i:], m.ReportType)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ReportType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RingId) > 0 {
		i -= len(m.RingId)
		copy(dAtA[i:], m.RingId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RingId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ReportId) > 0 {
		i -= len(m.ReportId)
		copy(dAtA[i:], m.ReportId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ReportId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRingAutoReshareScheduled) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRingAutoReshareScheduled) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRingAutoReshareScheduled) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Demerits != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Demerits))
		i--
		dAtA[i] = 0x28
	}
	if m.KickThreshold != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.KickThreshold))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ReplacementNodeKey) > 0 {
		i -= len(m.ReplacementNodeKey)
		copy(dAtA[i:], m.ReplacementNodeKey)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ReplacementNodeKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AccusedNodeKey) > 0 {
		i -= len(m.AccusedNodeKey)
		copy(dAtA[i:], m.AccusedNodeKey)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.AccusedNodeKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RingId) > 0 {
		i -= len(m.RingId)
		copy(dAtA[i:], m.RingId)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.RingId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventNodeKeyDrained) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventNodeKeyDrained) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventNodeKeyDrained) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvents(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.NodeKey) > 0 {
		i -= len(m.NodeKey)
		copy(dAtA[i:], m.NodeKey)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.NodeKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventRingCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RingId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.CreatorDid)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventRingUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RingId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.UpdaterDid)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventDocumentStored) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DocumentId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.CreatorDid)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventKeyDerivationStored) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.KeyDerivationId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.CreatorDid)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventNodeInfoCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PeerId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ControllerKey)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventNodeInfoUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PeerId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ControllerKey)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventRingDeleted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RingId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventRingUpgradeScheduled) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RingId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.CurrentVersion != 0 {
		n += 1 + sovEvents(uint64(m.CurrentVersion))
	}
	if m.NextVersion != 0 {
		n += 1 + sovEvents(uint64(m.NextVersion))
	}
	if m.ActivationTime != 0 {
		n += 1 + sovEvents(uint64(m.ActivationTime))
	}
	return n
}

func (m *EventRingUpgradeCancelled) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RingId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.CurrentVersion != 0 {
		n += 1 + sovEvents(uint64(m.CurrentVersion))
	}
	return n
}

func (m *EventRingUpgradeNormalized) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RingId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.PreviousVersion != 0 {
		n += 1 + sovEvents(uint64(m.PreviousVersion))
	}
	if m.CurrentVersion != 0 {
		n += 1 + sovEvents(uint64(m.CurrentVersion))
	}
	if m.ActivationTime != 0 {
		n += 1 + sovEvents(uint64(m.ActivationTime))
	}
	return n
}

func (m *EventReportAccepted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReportId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.RingId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ReportType)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ReporterNodeKey)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.AccusedNodeKey)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventRingAutoReshareScheduled) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RingId)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.AccusedNodeKey)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ReplacementNodeKey)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.KickThreshold != 0 {
		n += 1 + sovEvents(uint64(m.KickThreshold))
	}
	if m.Demerits != 0 {
		n += 1 + sovEvents(uint64(m.Demerits))
	}
	return n
}

func (m *EventNodeKeyDrained) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NodeKey)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovEvents(uint64(l))
		}
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventRingCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRingCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRingCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRingUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRingUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRingUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdaterDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdaterDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventDocumentStored) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDocumentStored: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDocumentStored: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocumentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocumentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventKeyDerivationStored) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventKeyDerivationStored: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventKeyDerivationStored: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyDerivationId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyDerivationId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventNodeInfoCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventNodeInfoCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventNodeInfoCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControllerKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ControllerKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventNodeInfoUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventNodeInfoUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventNodeInfoUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControllerKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ControllerKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRingDeleted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRingDeleted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRingDeleted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRingUpgradeScheduled) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRingUpgradeScheduled: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRingUpgradeScheduled: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentVersion", wireType)
			}
			m.CurrentVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextVersion", wireType)
			}
			m.NextVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationTime", wireType)
			}
			m.ActivationTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivationTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRingUpgradeCancelled) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRingUpgradeCancelled: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRingUpgradeCancelled: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentVersion", wireType)
			}
			m.CurrentVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRingUpgradeNormalized) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRingUpgradeNormalized: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRingUpgradeNormalized: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousVersion", wireType)
			}
			m.PreviousVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreviousVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentVersion", wireType)
			}
			m.CurrentVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationTime", wireType)
			}
			m.ActivationTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivationTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventReportAccepted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventReportAccepted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventReportAccepted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReportType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReporterNodeKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReporterNodeKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccusedNodeKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccusedNodeKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRingAutoReshareScheduled) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRingAutoReshareScheduled: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRingAutoReshareScheduled: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccusedNodeKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccusedNodeKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplacementNodeKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReplacementNodeKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KickThreshold", wireType)
			}
			m.KickThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KickThreshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Demerits", wireType)
			}
			m.Demerits = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Demerits |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventNodeKeyDrained) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventNodeKeyDrained: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventNodeKeyDrained: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
