// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sourcehub/orbis/key_derivation.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// KeyDerivation stores a signing derivation and its policy binding metadata.
type KeyDerivation struct {
	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorDid string `protobuf:"bytes,2,opt,name=creator_did,json=creatorDid,proto3" json:"creator_did,omitempty"`
	RingId     string `protobuf:"bytes,3,opt,name=ring_id,json=ringId,proto3" json:"ring_id,omitempty"`
	Derivation string `protobuf:"bytes,4,opt,name=derivation,proto3" json:"derivation,omitempty"`
	PolicyId   string `protobuf:"bytes,5,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Resource   string `protobuf:"bytes,6,opt,name=resource,proto3" json:"resource,omitempty"`
	Permission string `protobuf:"bytes,7,opt,name=permission,proto3" json:"permission,omitempty"`
}

func (m *KeyDerivation) Reset()         { *m = KeyDerivation{} }
func (m *KeyDerivation) String() string { return proto.CompactTextString(m) }
func (*KeyDerivation) ProtoMessage()    {}
func (*KeyDerivation) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ec7b253df726179, []int{0}
}
func (m *KeyDerivation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyDerivation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyDerivation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyDerivation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDerivation.Merge(m, src)
}
func (m *KeyDerivation) XXX_Size() int {
	return m.Size()
}
func (m *KeyDerivation) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDerivation.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDerivation proto.InternalMessageInfo

func (m *KeyDerivation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *KeyDerivation) GetCreatorDid() string {
	if m != nil {
		return m.CreatorDid
	}
	return ""
}

func (m *KeyDerivation) GetRingId() string {
	if m != nil {
		return m.RingId
	}
	return ""
}

func (m *KeyDerivation) GetDerivation() string {
	if m != nil {
		return m.Derivation
	}
	return ""
}

func (m *KeyDerivation) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *KeyDerivation) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *KeyDerivation) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

func init() {
	proto.RegisterType((*KeyDerivation)(nil), "sourcehub.orbis.KeyDerivation")
}

func init() {
	proto.RegisterFile("sourcehub/orbis/key_derivation.proto", fileDescriptor_4ec7b253df726179)
}

var fileDescriptor_4ec7b253df726179 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xeb, 0x00, 0x69, 0x7b, 0x08, 0x90, 0xbc, 0x60, 0x81, 0x64, 0x10, 0x62, 0x60, 0x6a,
	0x90, 0x78, 0x03, 0xd4, 0xa5, 0xb0, 0x31, 0xb2, 0x44, 0x4d, 0x6c, 0x95, 0x53, 0x69, 0x1c, 0x9d,
	0x5d, 0x20, 0x6f, 0xc1, 0x63, 0x31, 0x56, 0x4c, 0x8c, 0x28, 0x79, 0x11, 0x64, 0xbb, 0x34, 0xe3,
	0xfd, 0xff, 0x7f, 0x9f, 0xee, 0x7e, 0xb8, 0xb6, 0x66, 0x4d, 0xa5, 0x7e, 0x59, 0x17, 0x99, 0xa1,
	0x02, 0x6d, 0xb6, 0xd4, 0x4d, 0xae, 0x34, 0xe1, 0xdb, 0xdc, 0xa1, 0xa9, 0x26, 0x35, 0x19, 0x67,
	0xf8, 0xc9, 0x2e, 0x35, 0x09, 0xa9, 0xab, 0x6f, 0x06, 0x47, 0x8f, 0xba, 0x99, 0xee, 0x82, 0xfc,
	0x18, 0x12, 0x54, 0x82, 0x5d, 0xb2, 0x9b, 0xf1, 0x53, 0x82, 0x8a, 0x5f, 0xc0, 0x61, 0x49, 0x7a,
	0xee, 0x0c, 0xe5, 0x0a, 0x95, 0x48, 0x82, 0x01, 0x5b, 0x69, 0x8a, 0x8a, 0x9f, 0xc2, 0x90, 0xb0,
	0x5a, 0xe4, 0xa8, 0xc4, 0x5e, 0x30, 0x53, 0x3f, 0xce, 0x14, 0x97, 0x00, 0xfd, 0x01, 0x62, 0x3f,
	0x2e, 0xf6, 0x0a, 0x3f, 0x87, 0x71, 0x6d, 0x5e, 0xb1, 0x6c, 0xfc, 0xea, 0x41, 0xb0, 0x47, 0x51,
	0x98, 0x29, 0x7e, 0x06, 0x23, 0xd2, 0xf1, 0x5a, 0x91, 0x46, 0xef, 0x7f, 0xf6, 0xe0, 0x5a, 0xd3,
	0x0a, 0xad, 0xf5, 0xe0, 0x61, 0x04, 0xf7, 0xca, 0xfd, 0xc3, 0x57, 0x2b, 0xd9, 0xa6, 0x95, 0xec,
	0xb7, 0x95, 0xec, 0xb3, 0x93, 0x83, 0x4d, 0x27, 0x07, 0x3f, 0x9d, 0x1c, 0x3c, 0xdf, 0x2e, 0xd0,
	0xf9, 0xe7, 0x4b, 0xb3, 0xca, 0x22, 0xac, 0xd2, 0xee, 0xdd, 0xd0, 0x32, 0xeb, 0xeb, 0xfb, 0xd8,
	0x16, 0xe8, 0x9a, 0x5a, 0xdb, 0x22, 0x0d, 0xc5, 0xdd, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff, 0xcd,
	0x22, 0xbd, 0x61, 0x60, 0x01, 0x00, 0x00,
}

func (m *KeyDerivation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyDerivation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyDerivation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Permission) > 0 {
		i -= len(m.Permission)
		copy(dAtA[i:], m.Permission)
		i = encodeVarintKeyDerivation(dAtA, i, uint64(len(m.Permission)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Resource) > 0 {
		i -= len(m.Resource)
		copy(dAtA[i:], m.Resource)
		i = encodeVarintKeyDerivation(dAtA, i, uint64(len(m.Resource)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.PolicyId) > 0 {
		i -= len(m.PolicyId)
		copy(dAtA[i:], m.PolicyId)
		i = encodeVarintKeyDerivation(dAtA, i, uint64(len(m.PolicyId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Derivation) > 0 {
		i -= len(m.Derivation)
		copy(dAtA[i:], m.Derivation)
		i = encodeVarintKeyDerivation(dAtA, i, uint64(len(m.Derivation)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RingId) > 0 {
		i -= len(m.RingId)
		copy(dAtA[i:], m.RingId)
		i = encodeVarintKeyDerivation(dAtA, i, uint64(len(m.RingId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CreatorDid) > 0 {
		i -= len(m.CreatorDid)
		copy(dAtA[i:], m.CreatorDid)
		i = encodeVarintKeyDerivation(dAtA, i, uint64(len(m.CreatorDid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintKeyDerivation(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintKeyDerivation(dAtA []byte, offset int, v uint64) int {
	offset -= sovKeyDerivation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KeyDerivation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovKeyDerivation(uint64(l))
	}
	l = len(m.CreatorDid)
	if l > 0 {
		n += 1 + l + sovKeyDerivation(uint64(l))
	}
	l = len(m.RingId)
	if l > 0 {
		n += 1 + l + sovKeyDerivation(uint64(l))
	}
	l = len(m.Derivation)
	if l > 0 {
		n += 1 + l + sovKeyDerivation(uint64(l))
	}
	l = len(m.PolicyId)
	if l > 0 {
		n += 1 + l + sovKeyDerivation(uint64(l))
	}
	l = len(m.Resource)
	if l > 0 {
		n += 1 + l + sovKeyDerivation(uint64(l))
	}
	l = len(m.Permission)
	if l > 0 {
		n += 1 + l + sovKeyDerivation(uint64(l))
	}
	return n
}

func sovKeyDerivation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozKeyDerivation(x uint64) (n int) {
	return sovKeyDerivation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KeyDerivation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKeyDerivation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyDerivation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyDerivation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeyDerivation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeyDerivation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeyDerivation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Derivation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeyDerivation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Derivation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeyDerivation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Resource", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeyDerivation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Resource = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Permission", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeyDerivation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Permission = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipKeyDerivation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKeyDerivation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipKeyDerivation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowKeyDerivation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKeyDerivation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKeyDerivation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthKeyDerivation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupKeyDerivation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthKeyDerivation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthKeyDerivation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowKeyDerivation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupKeyDerivation = fmt.Errorf("proto: unexpected end of group")
)
