// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vera/orbis/node_info.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// NodeInfo stores access-control metadata for a node participating in Orbis rings.
type NodeInfo struct {
	// peer_id is the node's p2p network identity key.
	PeerId string `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// controller_key is the node's signing key changing node info. Lives outside the node
	ControllerKey        string   `protobuf:"bytes,2,opt,name=controller_key,json=controllerKey,proto3" json:"controller_key,omitempty"`
	WhitelistedPolicyIds []string `protobuf:"bytes,3,rep,name=whitelisted_policy_ids,json=whitelistedPolicyIds,proto3" json:"whitelisted_policy_ids,omitempty"`
	WhitelistedRingIds   []string `protobuf:"bytes,4,rep,name=whitelisted_ring_ids,json=whitelistedRingIds,proto3" json:"whitelisted_ring_ids,omitempty"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_707e1b52e20aed78, []int{0}
}
func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return m.Size()
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *NodeInfo) GetControllerKey() string {
	if m != nil {
		return m.ControllerKey
	}
	return ""
}

func (m *NodeInfo) GetWhitelistedPolicyIds() []string {
	if m != nil {
		return m.WhitelistedPolicyIds
	}
	return nil
}

func (m *NodeInfo) GetWhitelistedRingIds() []string {
	if m != nil {
		return m.WhitelistedRingIds
	}
	return nil
}

// NodeInfoEntry pairs a node_key with its NodeInfo for genesis export/import.
type NodeInfoEntry struct {
	// Node key lives inside the node and is for identification of the node
	NodeKey  string    `protobuf:"bytes,1,opt,name=node_key,json=nodeKey,proto3" json:"node_key,omitempty"`
	NodeInfo *NodeInfo `protobuf:"bytes,2,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
}

func (m *NodeInfoEntry) Reset()         { *m = NodeInfoEntry{} }
func (m *NodeInfoEntry) String() string { return proto.CompactTextString(m) }
func (*NodeInfoEntry) ProtoMessage()    {}
func (*NodeInfoEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_707e1b52e20aed78, []int{1}
}
func (m *NodeInfoEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeInfoEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NodeInfoEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NodeInfoEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfoEntry.Merge(m, src)
}
func (m *NodeInfoEntry) XXX_Size() int {
	return m.Size()
}
func (m *NodeInfoEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfoEntry.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfoEntry proto.InternalMessageInfo

func (m *NodeInfoEntry) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *NodeInfoEntry) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeInfo)(nil), "vera.orbis.NodeInfo")
	proto.RegisterType((*NodeInfoEntry)(nil), "vera.orbis.NodeInfoEntry")
}

func init() { proto.RegisterFile("vera/orbis/node_info.proto", fileDescriptor_707e1b52e20aed78) }

var fileDescriptor_707e1b52e20aed78 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0x1b, 0x2b, 0xfd, 0x88, 0xd4, 0x43, 0x28, 0x5a, 0x3d, 0x84, 0x52, 0x10, 0x0a, 0xc2,
	0xae, 0x5f, 0x4f, 0x20, 0xf4, 0xb0, 0x08, 0x22, 0x7b, 0x14, 0x24, 0xd8, 0xcd, 0xb4, 0x0d, 0x5d,
	0x33, 0x4b, 0x92, 0x5a, 0xf7, 0x2d, 0x7c, 0x16, 0x9f, 0xc2, 0x63, 0x8f, 0x1e, 0xa5, 0x7d, 0x11,
	0x49, 0xb4, 0x76, 0x6f, 0x33, 0xf3, 0x63, 0x86, 0xdf, 0xfc, 0xe9, 0xe9, 0x2b, 0x98, 0xe7, 0x18,
	0xcd, 0x58, 0xd9, 0x58, 0xa3, 0x04, 0xa1, 0xf4, 0x04, 0xa3, 0xc2, 0xa0, 0x43, 0x46, 0x3d, 0x8b,
	0x02, 0x1b, 0x7c, 0x10, 0xda, 0xba, 0x47, 0x09, 0x89, 0x9e, 0x20, 0x3b, 0xa6, 0xcd, 0x02, 0xc0,
	0x08, 0x25, 0x7b, 0xa4, 0x4f, 0x86, 0xed, 0xb4, 0xe1, 0xdb, 0x44, 0xb2, 0x33, 0x7a, 0x98, 0xa1,
	0x76, 0x06, 0xf3, 0x1c, 0x8c, 0x98, 0x43, 0xd9, 0xdb, 0x0b, 0xbc, 0xb3, 0x9b, 0xde, 0x41, 0xc9,
	0x6e, 0xe8, 0xd1, 0x72, 0xa6, 0x1c, 0xe4, 0xca, 0x3a, 0x90, 0xa2, 0xc0, 0x5c, 0x65, 0xa5, 0x50,
	0xd2, 0xf6, 0xea, 0xfd, 0xfa, 0xb0, 0x9d, 0x76, 0x2b, 0xf4, 0x21, 0xc0, 0x44, 0x5a, 0x76, 0x41,
	0xab, 0x73, 0x61, 0x94, 0x9e, 0x86, 0x9d, 0xfd, 0xb0, 0xc3, 0x2a, 0x2c, 0x55, 0x7a, 0x9a, 0x48,
	0x3b, 0x78, 0xa2, 0x9d, 0xad, 0xf3, 0x48, 0x3b, 0x53, 0xb2, 0x13, 0xda, 0x0a, 0x4f, 0x7a, 0xb3,
	0x5f, 0xf3, 0xa6, 0xef, 0xbd, 0xd3, 0x25, 0x6d, 0xff, 0xff, 0x1f, 0xac, 0x0f, 0xae, 0xba, 0xd1,
	0x2e, 0x80, 0x68, 0x7b, 0x28, 0x0d, 0x17, 0x7c, 0x75, 0x3b, 0xfa, 0x5c, 0x73, 0xb2, 0x5a, 0x73,
	0xf2, 0xbd, 0xe6, 0xe4, 0x7d, 0xc3, 0x6b, 0xab, 0x0d, 0xaf, 0x7d, 0x6d, 0x78, 0xed, 0xf1, 0x7c,
	0xaa, 0xdc, 0x6c, 0x31, 0x8e, 0x32, 0x7c, 0x89, 0x2d, 0x2e, 0x4c, 0x06, 0x1a, 0xdc, 0x12, 0xcd,
	0x3c, 0x0e, 0x71, 0xbf, 0xfd, 0x05, 0xee, 0xca, 0x02, 0xec, 0xb8, 0x11, 0xd2, 0xbe, 0xfe, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x32, 0xea, 0xef, 0xeb, 0x8b, 0x01, 0x00, 0x00,
}

func (m *NodeInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WhitelistedRingIds) > 0 {
		for iNdEx := len(m.WhitelistedRingIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WhitelistedRingIds[iNdEx])
			copy(dAtA[i:], m.WhitelistedRingIds[iNdEx])
			i = encodeVarintNodeInfo(dAtA, i, uint64(len(m.WhitelistedRingIds[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.WhitelistedPolicyIds) > 0 {
		for iNdEx := len(m.WhitelistedPolicyIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WhitelistedPolicyIds[iNdEx])
			copy(dAtA[i:], m.WhitelistedPolicyIds[iNdEx])
			i = encodeVarintNodeInfo(dAtA, i, uint64(len(m.WhitelistedPolicyIds[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ControllerKey) > 0 {
		i -= len(m.ControllerKey)
		copy(dAtA[i:], m.ControllerKey)
		i = encodeVarintNodeInfo(dAtA, i, uint64(len(m.ControllerKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PeerId) > 0 {
		i -= len(m.PeerId)
		copy(dAtA[i:], m.PeerId)
		i = encodeVarintNodeInfo(dAtA, i, uint64(len(m.PeerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NodeInfoEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeInfoEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeInfoEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NodeInfo != nil {
		{
			size, err := m.NodeInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNodeInfo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.NodeKey) > 0 {
		i -= len(m.NodeKey)
		copy(dAtA[i:], m.NodeKey)
		i = encodeVarintNodeInfo(dAtA, i, uint64(len(m.NodeKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintNodeInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovNodeInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NodeInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PeerId)
	if l > 0 {
		n += 1 + l + sovNodeInfo(uint64(l))
	}
	l = len(m.ControllerKey)
	if l > 0 {
		n += 1 + l + sovNodeInfo(uint64(l))
	}
	if len(m.WhitelistedPolicyIds) > 0 {
		for _, s := range m.WhitelistedPolicyIds {
			l = len(s)
			n += 1 + l + sovNodeInfo(uint64(l))
		}
	}
	if len(m.WhitelistedRingIds) > 0 {
		for _, s := range m.WhitelistedRingIds {
			l = len(s)
			n += 1 + l + sovNodeInfo(uint64(l))
		}
	}
	return n
}

func (m *NodeInfoEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NodeKey)
	if l > 0 {
		n += 1 + l + sovNodeInfo(uint64(l))
	}
	if m.NodeInfo != nil {
		l = m.NodeInfo.Size()
		n += 1 + l + sovNodeInfo(uint64(l))
	}
	return n
}

func sovNodeInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNodeInfo(x uint64) (n int) {
	return sovNodeInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NodeInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodeInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PeerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ControllerKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodeInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ControllerKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedPolicyIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodeInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedPolicyIds = append(m.WhitelistedPolicyIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedRingIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodeInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedRingIds = append(m.WhitelistedRingIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodeInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNodeInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeInfoEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodeInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeInfoEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeInfoEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodeInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodeInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodeInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNodeInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNodeInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NodeInfo == nil {
				m.NodeInfo = &NodeInfo{}
			}
			if err := m.NodeInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodeInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNodeInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNodeInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNodeInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodeInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodeInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNodeInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNodeInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNodeInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNodeInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNodeInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNodeInfo = fmt.Errorf("proto: unexpected end of group")
)
