syntax = "proto3";
package vera.feegrant.v1beta1;

import "gogoproto/gogo.proto";
import "vera/feegrant/v1beta1/feegrant.proto";
import "amino/amino.proto";

option go_package = "github.com/sourcenetwork/vera/x/feegrant";

// GenesisState contains a set of fee allowances, persisted from the store.
message GenesisState {
  repeated Grant allowances = 1 [(gogoproto.nullable) = false, (amino.dont_omitempty) = true];
  repeated DIDGrant did_allowances = 2 [(gogoproto.nullable) = false, (amino.dont_omitempty) = true];
}