syntax = "proto3";
package vera.tier.v1beta1;

import "amino/amino.proto";
import "cosmos/base/v1beta1/coin.proto";
import "cosmos/msg/v1/msg.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "google/protobuf/timestamp.proto";
import "vera/tier/v1beta1/params.proto";

option go_package = "github.com/sourcenetwork/vera/x/tier/types";

// Msg defines the Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  // UpdateParams defines a (governance) operation for updating the module
  // parameters. The authority defaults to the x/gov module account.
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);

  // Lock defines a (developer) operation for locking a stake.
  rpc Lock(MsgLock) returns (MsgLockResponse);

  // LockAuto defines a (developer) operation for locking a stake with automatic validator selection.
  rpc LockAuto(MsgLockAuto) returns (MsgLockAutoResponse);

  // Unlock defines a (developer) operation for unlocking a stake.
  rpc Unlock(MsgUnlock) returns (MsgUnlockResponse);

  // Redelegate defines a (developer) operation for re-delegating a stake.
  rpc Redelegate(MsgRedelegate) returns (MsgRedelegateResponse);

  // CancelUnlocking defines a (developer) operation for canceling an unlocking stake.
  rpc CancelUnlocking(MsgCancelUnlocking) returns (MsgCancelUnlockingResponse);

  // CreateDeveloper defines a (developer) operation for creating a new developer record.
  rpc CreateDeveloper(MsgCreateDeveloper) returns (MsgCreateDeveloperResponse);

  // UpdateDeveloper defines a (developer) operation for updating an existing developer record.
  rpc UpdateDeveloper(MsgUpdateDeveloper) returns (MsgUpdateDeveloperResponse);

  // RemoveDeveloper defines a (developer) operation for removing a developer record.
  rpc RemoveDeveloper(MsgRemoveDeveloper) returns (MsgRemoveDeveloperResponse);

  // AddUserSubscription defines a (developer) operation for adding a user subscription.
  rpc AddUserSubscription(MsgAddUserSubscription) returns (MsgAddUserSubscriptionResponse);

  // UpdateUserSubscription defines a (developer) operation for updating a user subscription.
  rpc UpdateUserSubscription(MsgUpdateUserSubscription) returns (MsgUpdateUserSubscriptionResponse);

  // RemoveUserSubscription defines a (developer) operation for removing a user subscription.
  // This expires the allowance at the end of the current period rather than immediately revoking it.
  rpc RemoveUserSubscription(MsgRemoveUserSubscription) returns (MsgRemoveUserSubscriptionResponse);
}

// MsgUpdateParams is the Msg/UpdateParams request type.
message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name) = "vera/x/tier/MsgUpdateParams";

  // authority is the address that controls the module (defaults to x/gov unless overwritten).
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  // params defines the module parameters to update.

  // NOTE: All parameters must be supplied.
  Params params = 2 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
message MsgUpdateParamsResponse {}

// MsgLock is the Msg/Lock request type.
message MsgLock {
  option (cosmos.msg.v1.signer) = "delegator_address";
  string delegator_address = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string validator_address = 2 [(cosmos_proto.scalar) = "cosmos.ValidatorAddressString"];
  cosmos.base.v1beta1.Coin stake = 3 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// MsgLockResponse defines the response structure for executing a MsgLock message.
message MsgLockResponse {}

// MsgLockAuto is the Msg/LockAuto request type.
message MsgLockAuto {
  option (cosmos.msg.v1.signer) = "delegator_address";
  string delegator_address = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  cosmos.base.v1beta1.Coin stake = 2 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// MsgLockAutoResponse defines the response structure for executing a MsgLockAuto message.
message MsgLockAutoResponse {
  string validator_address = 1 [(cosmos_proto.scalar) = "cosmos.ValidatorAddressString"];
}

// MsgUnlock is the Msg/Unlock request type.
message MsgUnlock {
  option (cosmos.msg.v1.signer) = "delegator_address";
  string delegator_address = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string validator_address = 2 [(cosmos_proto.scalar) = "cosmos.ValidatorAddressString"];
  cosmos.base.v1beta1.Coin stake = 3 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// MsgUnlockResponse defines the response structure for executing a MsgUnlock message.
message MsgUnlockResponse {
  int64 creation_height = 1;
  google.protobuf.Timestamp completion_time = 2 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true,
    (gogoproto.stdtime) = true
  ];
  google.protobuf.Timestamp unlock_time = 3 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true,
    (gogoproto.stdtime) = true
  ];
}

// MsgRedelegate is the Msg/Redelegate request type.
message MsgRedelegate {
  option (cosmos.msg.v1.signer) = "delegator_address";
  string delegator_address = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string src_validator_address = 2 [(cosmos_proto.scalar) = "cosmos.ValidatorAddressString"];
  string dst_validator_address = 3 [(cosmos_proto.scalar) = "cosmos.ValidatorAddressString"];
  cosmos.base.v1beta1.Coin stake = 4 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// MsgRedelegateResponse defines the response structure for executing a MsgRedelegate message.
message MsgRedelegateResponse {
  google.protobuf.Timestamp completion_time = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true,
    (gogoproto.stdtime) = true
  ];
}

// MsgCancelUnlocking is the Msg/CancelUnlocking request type.
message MsgCancelUnlocking {
  option (cosmos.msg.v1.signer) = "delegator_address";
  string delegator_address = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  string validator_address = 2 [(cosmos_proto.scalar) = "cosmos.ValidatorAddressString"];
  // amount is always less than or equal to unlocking delegation entry balance.
  cosmos.base.v1beta1.Coin stake = 3 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  // creation_height is the height which the unlocking took place.
  int64 creation_height = 4;
}

// MsgCancelUnlockingResponse defines the response structure for executing a MsgCancelUnlocking message.
message MsgCancelUnlockingResponse {}

// MsgCreateDeveloper is the Msg/CreateDeveloper request type.
message MsgCreateDeveloper {
  option (cosmos.msg.v1.signer) = "developer";
  // developer is the address of the developer being created.
  string developer = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  // auto_lock_enabled indicates whether the module should automatically lock more #OPEN tokens, 
  // so that the developer always has enough credits to cover all active user subscriptions.
  bool auto_lock_enabled = 2;
}

// MsgCreateDeveloperResponse defines the response structure for executing a MsgCreateDeveloper message.
message MsgCreateDeveloperResponse {}

// MsgUpdateDeveloper is the Msg/UpdateDeveloper request type.
message MsgUpdateDeveloper {
  option (cosmos.msg.v1.signer) = "developer";
  // developer is the address of the developer being updated.
  string developer = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  // auto_lock_enabled indicates whether the module should automatically lock more #OPEN tokens, 
  // so that the developer always has enough credits to cover all active user subscriptions.
  bool auto_lock_enabled = 2;
}

// MsgUpdateDeveloperResponse defines the response structure for executing a MsgUpdateDeveloper message.
message MsgUpdateDeveloperResponse {}

// MsgRemoveDeveloper is the Msg/RemoveDeveloper request type.
message MsgRemoveDeveloper {
  option (cosmos.msg.v1.signer) = "developer";
  // developer is the address of the developer being removed.
  string developer = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
}

// MsgRemoveDeveloperResponse defines the response structure for executing a MsgRemoveDeveloper message.
message MsgRemoveDeveloperResponse {}

// MsgAddUserSubscription is the Msg/AddUserSubscription request type.
message MsgAddUserSubscription {
  option (cosmos.msg.v1.signer) = "developer";
  // developer is the address of the developer adding the subscription.
  string developer = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  // user_did is the DID of the user being added to the subscription.
  string user_did = 2;
  // amount is the credit amount to be allocated to the user per period.
  uint64 amount = 3;
  // period is the subscription period duration in seconds.
  uint64 period = 4;
}

// MsgAddUserSubscriptionResponse defines the response structure for executing a MsgAddUserSubscription message.
message MsgAddUserSubscriptionResponse {}

// MsgUpdateUserSubscription is the Msg/UpdateUserSubscription request type.
message MsgUpdateUserSubscription {
  option (cosmos.msg.v1.signer) = "developer";
  // developer is the address of the developer updating the subscription.
  string developer = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  // user_did is the DID of the user whose subscription is being updated.
  string user_did = 2;
  // amount is the new credit amount to be allocated to the user per period.
  uint64 amount = 3;
  // period is the new subscription period duration in seconds.
  uint64 period = 4;
}

// MsgUpdateUserSubscriptionResponse defines the response structure for executing a MsgUpdateUserSubscription message.
message MsgUpdateUserSubscriptionResponse {}

// MsgRemoveUserSubscription is the Msg/RemoveUserSubscription request type.
// This message removes the user subscription and expires the associated allowance at the end of the current period.
message MsgRemoveUserSubscription {
  option (cosmos.msg.v1.signer) = "developer";
  // developer is the address of the developer removing the subscription.
  string developer = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];
  // user_did is the DID of the user whose subscription is being removed.
  string user_did = 2;
}

// MsgRemoveUserSubscriptionResponse defines the response structure for executing a MsgRemoveUserSubscription message.
message MsgRemoveUserSubscriptionResponse {}
