package types

const (
	EventTypeCancelUnlocking                      = "cancel_unlocking"
	EventTypeCompleteUnlocking                    = "complete_unlocking"
	EventTypeLock                                 = "lock"
	EventTypeRedelegate                           = "redelegate"
	EventTypeUnlock                               = "unlock"
	EventTypeDeveloperCreated                     = "developer_created"
	EventTypeDeveloperUpdated                     = "developer_updated"
	EventTypeDeveloperRemoved                     = "developer_removed"
	EventTypeUserSubscriptionCreated              = "user_subscription_created"
	EventTypeUserSubscriptionUpdated              = "user_subscription_updated"
	EventTypeUserSubscriptionRemoved              = "user_subscription_removed"
	EventTypeDeveloperInsufficientCredits         = "developer_insufficient_credits"
	EventTypeDeveloperInsufficientOpenForAutoLock = "developer_insufficient_open_for_auto_lock"
	EventTypeDeveloperAutoLockFailed              = "developer_auto_lock_failed"
	EventTypeDeveloperAutoLockSuccess             = "developer_auto_lock_success"

	AttributeKeyCompletionTime         = "completion_time"
	AttributeKeyCreationHeight         = "creation_height"
	AttributeCreditAmount              = "credit_amount"
	AttributeKeyDestinationValidator   = "destination_validator"
	AttributeKeySourceValidator        = "source_validator"
	AttributeKeyUnlockTime             = "unlock_time"
	AttributeKeyDeveloper              = "developer"
	AttributeKeyUser                   = "user"
	AttributeKeySubscriptionPeriod     = "subscription_period"
	AttributeKeySubscriptionAmount     = "subscription_amount"
	AttributeKeySubscriptionExpiration = "subscription_expiration"
	AttributeKeyCurrentBalance         = "current_balance"
	AttributeKeyTotalGranted           = "total_granted"
	AttributeKeyUopenBalance           = "uopen_balance"
	AttributeKeyRequiredLockAmount     = "required_lock_amount"
	AttributeKeyAutoLockEnabled        = "auto_lock_enabled"
	AttributeKeyError                  = "error"
	AttributeKeyLockAmount             = "lock_amount"
)
