syntax = "proto3";
package sourcehub.ica;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "sourcehub/ica/params.proto";
import "sourcehub/ica/ica_connection.proto";

option go_package = "github.com/sourcenetwork/sourcehub/x/ica/types";

// GenesisState defines the ica module's genesis state.
message GenesisState {
  // params defines all the parameters of the module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];

  // ica_connections defines the list of ICA connections.
  repeated ICAConnection ica_connections = 2 [(gogoproto.nullable) = false];
}