// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sourcehub/tier/v1beta1/query.proto

package tierv1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Params_FullMethodName           = "/sourcehub.tier.v1beta1.Query/Params"
	Query_Lockup_FullMethodName           = "/sourcehub.tier.v1beta1.Query/Lockup"
	Query_Lockups_FullMethodName          = "/sourcehub.tier.v1beta1.Query/Lockups"
	Query_UnlockingLockup_FullMethodName  = "/sourcehub.tier.v1beta1.Query/UnlockingLockup"
	Query_UnlockingLockups_FullMethodName = "/sourcehub.tier.v1beta1.Query/UnlockingLockups"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC querier service.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Lockup queries a lockup by delegator and validator address.
	Lockup(ctx context.Context, in *LockupRequest, opts ...grpc.CallOption) (*LockupResponse, error)
	// Lockups queries all the lockups of a delegator.
	Lockups(ctx context.Context, in *LockupsRequest, opts ...grpc.CallOption) (*LockupsResponse, error)
	// UnlockingLockup queries an unlocking lockup by delegator and validator address.
	UnlockingLockup(ctx context.Context, in *UnlockingLockupRequest, opts ...grpc.CallOption) (*UnlockingLockupResponse, error)
	// UnlockingLockups queries all the unlocking lockups of a delegator.
	UnlockingLockups(ctx context.Context, in *UnlockingLockupsRequest, opts ...grpc.CallOption) (*UnlockingLockupsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Lockup(ctx context.Context, in *LockupRequest, opts ...grpc.CallOption) (*LockupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockupResponse)
	err := c.cc.Invoke(ctx, Query_Lockup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Lockups(ctx context.Context, in *LockupsRequest, opts ...grpc.CallOption) (*LockupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockupsResponse)
	err := c.cc.Invoke(ctx, Query_Lockups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UnlockingLockup(ctx context.Context, in *UnlockingLockupRequest, opts ...grpc.CallOption) (*UnlockingLockupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockingLockupResponse)
	err := c.cc.Invoke(ctx, Query_UnlockingLockup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UnlockingLockups(ctx context.Context, in *UnlockingLockupsRequest, opts ...grpc.CallOption) (*UnlockingLockupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockingLockupsResponse)
	err := c.cc.Invoke(ctx, Query_UnlockingLockups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC querier service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Lockup queries a lockup by delegator and validator address.
	Lockup(context.Context, *LockupRequest) (*LockupResponse, error)
	// Lockups queries all the lockups of a delegator.
	Lockups(context.Context, *LockupsRequest) (*LockupsResponse, error)
	// UnlockingLockup queries an unlocking lockup by delegator and validator address.
	UnlockingLockup(context.Context, *UnlockingLockupRequest) (*UnlockingLockupResponse, error)
	// UnlockingLockups queries all the unlocking lockups of a delegator.
	UnlockingLockups(context.Context, *UnlockingLockupsRequest) (*UnlockingLockupsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Lockup(context.Context, *LockupRequest) (*LockupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lockup not implemented")
}
func (UnimplementedQueryServer) Lockups(context.Context, *LockupsRequest) (*LockupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lockups not implemented")
}
func (UnimplementedQueryServer) UnlockingLockup(context.Context, *UnlockingLockupRequest) (*UnlockingLockupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockingLockup not implemented")
}
func (UnimplementedQueryServer) UnlockingLockups(context.Context, *UnlockingLockupsRequest) (*UnlockingLockupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockingLockups not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Lockup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Lockup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Lockup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Lockup(ctx, req.(*LockupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Lockups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Lockups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Lockups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Lockups(ctx, req.(*LockupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UnlockingLockup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockingLockupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UnlockingLockup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_UnlockingLockup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UnlockingLockup(ctx, req.(*UnlockingLockupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UnlockingLockups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockingLockupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UnlockingLockups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_UnlockingLockups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UnlockingLockups(ctx, req.(*UnlockingLockupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sourcehub.tier.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Lockup",
			Handler:    _Query_Lockup_Handler,
		},
		{
			MethodName: "Lockups",
			Handler:    _Query_Lockups_Handler,
		},
		{
			MethodName: "UnlockingLockup",
			Handler:    _Query_UnlockingLockup_Handler,
		},
		{
			MethodName: "UnlockingLockups",
			Handler:    _Query_UnlockingLockups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sourcehub/tier/v1beta1/query.proto",
}
