// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sourcehub/faucet/faucet.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FaucetRequestRecord represents a faucet request record stored internally.
type FaucetRequestRecord struct {
	Address string     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount  types.Coin `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount"`
	TxHash  string     `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
}

func (m *FaucetRequestRecord) Reset()         { *m = FaucetRequestRecord{} }
func (m *FaucetRequestRecord) String() string { return proto.CompactTextString(m) }
func (*FaucetRequestRecord) ProtoMessage()    {}
func (*FaucetRequestRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_b854b66c8024df8a, []int{0}
}
func (m *FaucetRequestRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FaucetRequestRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FaucetRequestRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FaucetRequestRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaucetRequestRecord.Merge(m, src)
}
func (m *FaucetRequestRecord) XXX_Size() int {
	return m.Size()
}
func (m *FaucetRequestRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_FaucetRequestRecord.DiscardUnknown(m)
}

var xxx_messageInfo_FaucetRequestRecord proto.InternalMessageInfo

func (m *FaucetRequestRecord) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *FaucetRequestRecord) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *FaucetRequestRecord) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

// FaucetRequest represents a request to get funds from the faucet.
type FaucetRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *FaucetRequest) Reset()         { *m = FaucetRequest{} }
func (m *FaucetRequest) String() string { return proto.CompactTextString(m) }
func (*FaucetRequest) ProtoMessage()    {}
func (*FaucetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b854b66c8024df8a, []int{1}
}
func (m *FaucetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FaucetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FaucetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FaucetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaucetRequest.Merge(m, src)
}
func (m *FaucetRequest) XXX_Size() int {
	return m.Size()
}
func (m *FaucetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FaucetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FaucetRequest proto.InternalMessageInfo

func (m *FaucetRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// FaucetResponse represents the response from a faucet request.
type FaucetResponse struct {
	Txhash  string     `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	Code    uint32     `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	RawLog  string     `protobuf:"bytes,3,opt,name=raw_log,json=rawLog,proto3" json:"raw_log,omitempty"`
	Address string     `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Amount  types.Coin `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount"`
}

func (m *FaucetResponse) Reset()         { *m = FaucetResponse{} }
func (m *FaucetResponse) String() string { return proto.CompactTextString(m) }
func (*FaucetResponse) ProtoMessage()    {}
func (*FaucetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b854b66c8024df8a, []int{2}
}
func (m *FaucetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FaucetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FaucetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FaucetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaucetResponse.Merge(m, src)
}
func (m *FaucetResponse) XXX_Size() int {
	return m.Size()
}
func (m *FaucetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FaucetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FaucetResponse proto.InternalMessageInfo

func (m *FaucetResponse) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *FaucetResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FaucetResponse) GetRawLog() string {
	if m != nil {
		return m.RawLog
	}
	return ""
}

func (m *FaucetResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *FaucetResponse) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

// InitAccountRequest represents a request to initialize an account.
type InitAccountRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *InitAccountRequest) Reset()         { *m = InitAccountRequest{} }
func (m *InitAccountRequest) String() string { return proto.CompactTextString(m) }
func (*InitAccountRequest) ProtoMessage()    {}
func (*InitAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b854b66c8024df8a, []int{3}
}
func (m *InitAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InitAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InitAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InitAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitAccountRequest.Merge(m, src)
}
func (m *InitAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *InitAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitAccountRequest proto.InternalMessageInfo

func (m *InitAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// InitAccountResponse represents the response from an account initialization request.
type InitAccountResponse struct {
	Message string     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Txhash  string     `protobuf:"bytes,2,opt,name=txhash,proto3" json:"txhash,omitempty"`
	Code    uint32     `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	RawLog  string     `protobuf:"bytes,4,opt,name=raw_log,json=rawLog,proto3" json:"raw_log,omitempty"`
	Address string     `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Amount  types.Coin `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount"`
	Exists  bool       `protobuf:"varint,7,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (m *InitAccountResponse) Reset()         { *m = InitAccountResponse{} }
func (m *InitAccountResponse) String() string { return proto.CompactTextString(m) }
func (*InitAccountResponse) ProtoMessage()    {}
func (*InitAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b854b66c8024df8a, []int{4}
}
func (m *InitAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InitAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InitAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InitAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitAccountResponse.Merge(m, src)
}
func (m *InitAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *InitAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitAccountResponse proto.InternalMessageInfo

func (m *InitAccountResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *InitAccountResponse) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *InitAccountResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *InitAccountResponse) GetRawLog() string {
	if m != nil {
		return m.RawLog
	}
	return ""
}

func (m *InitAccountResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InitAccountResponse) GetAmount() types.Coin {
	if m != nil {
		return m.Amount
	}
	return types.Coin{}
}

func (m *InitAccountResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

// FaucetInfoResponse represents the faucet information response.
type FaucetInfoResponse struct {
	Address      string     `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance      types.Coin `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance"`
	RequestCount int32      `protobuf:"varint,3,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
}

func (m *FaucetInfoResponse) Reset()         { *m = FaucetInfoResponse{} }
func (m *FaucetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*FaucetInfoResponse) ProtoMessage()    {}
func (*FaucetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b854b66c8024df8a, []int{5}
}
func (m *FaucetInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FaucetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FaucetInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FaucetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaucetInfoResponse.Merge(m, src)
}
func (m *FaucetInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *FaucetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FaucetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FaucetInfoResponse proto.InternalMessageInfo

func (m *FaucetInfoResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *FaucetInfoResponse) GetBalance() types.Coin {
	if m != nil {
		return m.Balance
	}
	return types.Coin{}
}

func (m *FaucetInfoResponse) GetRequestCount() int32 {
	if m != nil {
		return m.RequestCount
	}
	return 0
}

// GrantAllowanceRequest represents a request to grant fee allowance from the faucet.
type GrantAllowanceRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Optional amount limit for the allowance (in uopen). If not provided, defaults to 10000000000 (10,000 OPEN)
	AmountLimit types.Coin `protobuf:"bytes,2,opt,name=amount_limit,json=amountLimit,proto3" json:"amount_limit"`
	// Optional expiration time in unix timestamp. If not provided, defaults to 30 days from now
	Expiration int64 `protobuf:"varint,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (m *GrantAllowanceRequest) Reset()         { *m = GrantAllowanceRequest{} }
func (m *GrantAllowanceRequest) String() string { return proto.CompactTextString(m) }
func (*GrantAllowanceRequest) ProtoMessage()    {}
func (*GrantAllowanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b854b66c8024df8a, []int{6}
}
func (m *GrantAllowanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GrantAllowanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GrantAllowanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GrantAllowanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantAllowanceRequest.Merge(m, src)
}
func (m *GrantAllowanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *GrantAllowanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantAllowanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrantAllowanceRequest proto.InternalMessageInfo

func (m *GrantAllowanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GrantAllowanceRequest) GetAmountLimit() types.Coin {
	if m != nil {
		return m.AmountLimit
	}
	return types.Coin{}
}

func (m *GrantAllowanceRequest) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

// GrantAllowanceResponse represents the response from a grant allowance request.
type GrantAllowanceResponse struct {
	Message     string     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Txhash      string     `protobuf:"bytes,2,opt,name=txhash,proto3" json:"txhash,omitempty"`
	Code        uint32     `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	RawLog      string     `protobuf:"bytes,4,opt,name=raw_log,json=rawLog,proto3" json:"raw_log,omitempty"`
	Granter     string     `protobuf:"bytes,5,opt,name=granter,proto3" json:"granter,omitempty"`
	Grantee     string     `protobuf:"bytes,6,opt,name=grantee,proto3" json:"grantee,omitempty"`
	AmountLimit types.Coin `protobuf:"bytes,7,opt,name=amount_limit,json=amountLimit,proto3" json:"amount_limit"`
	Expiration  int64      `protobuf:"varint,8,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (m *GrantAllowanceResponse) Reset()         { *m = GrantAllowanceResponse{} }
func (m *GrantAllowanceResponse) String() string { return proto.CompactTextString(m) }
func (*GrantAllowanceResponse) ProtoMessage()    {}
func (*GrantAllowanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b854b66c8024df8a, []int{7}
}
func (m *GrantAllowanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GrantAllowanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GrantAllowanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GrantAllowanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantAllowanceResponse.Merge(m, src)
}
func (m *GrantAllowanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *GrantAllowanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantAllowanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrantAllowanceResponse proto.InternalMessageInfo

func (m *GrantAllowanceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GrantAllowanceResponse) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *GrantAllowanceResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GrantAllowanceResponse) GetRawLog() string {
	if m != nil {
		return m.RawLog
	}
	return ""
}

func (m *GrantAllowanceResponse) GetGranter() string {
	if m != nil {
		return m.Granter
	}
	return ""
}

func (m *GrantAllowanceResponse) GetGrantee() string {
	if m != nil {
		return m.Grantee
	}
	return ""
}

func (m *GrantAllowanceResponse) GetAmountLimit() types.Coin {
	if m != nil {
		return m.AmountLimit
	}
	return types.Coin{}
}

func (m *GrantAllowanceResponse) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

// GrantDIDAllowanceRequest represents a request to grant fee allowance to a DID from the faucet.
type GrantDIDAllowanceRequest struct {
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	// Optional amount limit for the allowance (in uopen). If not provided, defaults to 10000000000 (10,000 OPEN)
	AmountLimit types.Coin `protobuf:"bytes,2,opt,name=amount_limit,json=amountLimit,proto3" json:"amount_limit"`
	// Optional expiration time in unix timestamp. If not provided, defaults to 30 days from now
	Expiration int64 `protobuf:"varint,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (m *GrantDIDAllowanceRequest) Reset()         { *m = GrantDIDAllowanceRequest{} }
func (m *GrantDIDAllowanceRequest) String() string { return proto.CompactTextString(m) }
func (*GrantDIDAllowanceRequest) ProtoMessage()    {}
func (*GrantDIDAllowanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b854b66c8024df8a, []int{8}
}
func (m *GrantDIDAllowanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GrantDIDAllowanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GrantDIDAllowanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GrantDIDAllowanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantDIDAllowanceRequest.Merge(m, src)
}
func (m *GrantDIDAllowanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *GrantDIDAllowanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantDIDAllowanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrantDIDAllowanceRequest proto.InternalMessageInfo

func (m *GrantDIDAllowanceRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *GrantDIDAllowanceRequest) GetAmountLimit() types.Coin {
	if m != nil {
		return m.AmountLimit
	}
	return types.Coin{}
}

func (m *GrantDIDAllowanceRequest) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

// GrantDIDAllowanceResponse represents the response from a DID grant allowance request.
type GrantDIDAllowanceResponse struct {
	Message     string     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Txhash      string     `protobuf:"bytes,2,opt,name=txhash,proto3" json:"txhash,omitempty"`
	Code        uint32     `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	RawLog      string     `protobuf:"bytes,4,opt,name=raw_log,json=rawLog,proto3" json:"raw_log,omitempty"`
	Granter     string     `protobuf:"bytes,5,opt,name=granter,proto3" json:"granter,omitempty"`
	GranteeDid  string     `protobuf:"bytes,6,opt,name=grantee_did,json=granteeDid,proto3" json:"grantee_did,omitempty"`
	AmountLimit types.Coin `protobuf:"bytes,7,opt,name=amount_limit,json=amountLimit,proto3" json:"amount_limit"`
	Expiration  int64      `protobuf:"varint,8,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (m *GrantDIDAllowanceResponse) Reset()         { *m = GrantDIDAllowanceResponse{} }
func (m *GrantDIDAllowanceResponse) String() string { return proto.CompactTextString(m) }
func (*GrantDIDAllowanceResponse) ProtoMessage()    {}
func (*GrantDIDAllowanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b854b66c8024df8a, []int{9}
}
func (m *GrantDIDAllowanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GrantDIDAllowanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GrantDIDAllowanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GrantDIDAllowanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantDIDAllowanceResponse.Merge(m, src)
}
func (m *GrantDIDAllowanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *GrantDIDAllowanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantDIDAllowanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrantDIDAllowanceResponse proto.InternalMessageInfo

func (m *GrantDIDAllowanceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GrantDIDAllowanceResponse) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *GrantDIDAllowanceResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GrantDIDAllowanceResponse) GetRawLog() string {
	if m != nil {
		return m.RawLog
	}
	return ""
}

func (m *GrantDIDAllowanceResponse) GetGranter() string {
	if m != nil {
		return m.Granter
	}
	return ""
}

func (m *GrantDIDAllowanceResponse) GetGranteeDid() string {
	if m != nil {
		return m.GranteeDid
	}
	return ""
}

func (m *GrantDIDAllowanceResponse) GetAmountLimit() types.Coin {
	if m != nil {
		return m.AmountLimit
	}
	return types.Coin{}
}

func (m *GrantDIDAllowanceResponse) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func init() {
	proto.RegisterType((*FaucetRequestRecord)(nil), "sourcehub.faucet.FaucetRequestRecord")
	proto.RegisterType((*FaucetRequest)(nil), "sourcehub.faucet.FaucetRequest")
	proto.RegisterType((*FaucetResponse)(nil), "sourcehub.faucet.FaucetResponse")
	proto.RegisterType((*InitAccountRequest)(nil), "sourcehub.faucet.InitAccountRequest")
	proto.RegisterType((*InitAccountResponse)(nil), "sourcehub.faucet.InitAccountResponse")
	proto.RegisterType((*FaucetInfoResponse)(nil), "sourcehub.faucet.FaucetInfoResponse")
	proto.RegisterType((*GrantAllowanceRequest)(nil), "sourcehub.faucet.GrantAllowanceRequest")
	proto.RegisterType((*GrantAllowanceResponse)(nil), "sourcehub.faucet.GrantAllowanceResponse")
	proto.RegisterType((*GrantDIDAllowanceRequest)(nil), "sourcehub.faucet.GrantDIDAllowanceRequest")
	proto.RegisterType((*GrantDIDAllowanceResponse)(nil), "sourcehub.faucet.GrantDIDAllowanceResponse")
}

func init() { proto.RegisterFile("sourcehub/faucet/faucet.proto", fileDescriptor_b854b66c8024df8a) }

var fileDescriptor_b854b66c8024df8a = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xce, 0x26, 0xad, 0xdd, 0x4e, 0xdb, 0x9f, 0xfa, 0xdb, 0x42, 0x71, 0x2b, 0xe1, 0x56, 0xe6,
	0x52, 0x38, 0xd8, 0x2a, 0xbd, 0x22, 0xa4, 0xfe, 0x11, 0xa5, 0x52, 0xb9, 0xf8, 0xc8, 0xc5, 0xda,
	0xd8, 0x5b, 0xc7, 0x22, 0xf6, 0x1a, 0xef, 0x86, 0x84, 0x17, 0xe0, 0x8c, 0x04, 0x5c, 0x38, 0x70,
	0xe6, 0x82, 0xc4, 0x63, 0xf4, 0xd8, 0x23, 0x27, 0x84, 0x12, 0x24, 0x5e, 0x03, 0x79, 0x77, 0xdd,
	0xa6, 0x24, 0x51, 0x15, 0x04, 0xe5, 0x92, 0xec, 0xcc, 0xec, 0xec, 0xcc, 0xf7, 0x7d, 0x63, 0x0d,
	0xdc, 0xe6, 0xac, 0x53, 0x84, 0xb4, 0xd5, 0x69, 0x7a, 0x27, 0xa4, 0x13, 0x52, 0xa1, 0xff, 0xdc,
	0xbc, 0x60, 0x82, 0xe1, 0xe5, 0xf3, 0xb0, 0xab, 0xfc, 0xeb, 0xff, 0x93, 0x34, 0xc9, 0x98, 0x27,
	0x7f, 0xd5, 0xa5, 0xf5, 0xb5, 0x90, 0xf1, 0x94, 0xf1, 0x40, 0x5a, 0x9e, 0x32, 0x74, 0xe8, 0x46,
	0xcc, 0x62, 0xa6, 0xfc, 0xe5, 0x49, 0x7b, 0x6d, 0x75, 0xc7, 0x6b, 0x12, 0x4e, 0xbd, 0x17, 0xdb,
	0x4d, 0x2a, 0xc8, 0xb6, 0x17, 0xb2, 0x24, 0x53, 0x71, 0xe7, 0x15, 0x82, 0x95, 0x47, 0xb2, 0x9c,
	0x4f, 0x9f, 0x77, 0x28, 0x17, 0x3e, 0x0d, 0x59, 0x11, 0x61, 0x0b, 0x4c, 0x12, 0x45, 0x05, 0xe5,
	0xdc, 0x42, 0x9b, 0x68, 0x6b, 0xde, 0xaf, 0x4c, 0xfc, 0x00, 0x0c, 0x92, 0xb2, 0x4e, 0x26, 0xac,
	0xfa, 0x26, 0xda, 0x5a, 0xb8, 0xbf, 0xe6, 0xea, 0x36, 0xca, 0x12, 0xae, 0x2e, 0xe1, 0xee, 0xb3,
	0x24, 0xdb, 0x9b, 0x3f, 0xfd, 0xba, 0x51, 0xfb, 0xf8, 0xe3, 0xf3, 0x3d, 0xe4, 0xeb, 0x1c, 0x7c,
	0x0b, 0x4c, 0xd1, 0x0b, 0x5a, 0x84, 0xb7, 0xac, 0x86, 0x7c, 0xd7, 0x10, 0xbd, 0xc7, 0x84, 0xb7,
	0x9c, 0xbb, 0xb0, 0x74, 0xa9, 0x8f, 0xc9, 0x1d, 0x38, 0x9f, 0x10, 0xfc, 0x57, 0xdd, 0xe5, 0x39,
	0xcb, 0x38, 0xc5, 0xab, 0x60, 0x88, 0x9e, 0x7c, 0x15, 0x55, 0xaf, 0x96, 0x16, 0xc6, 0x30, 0x13,
	0xb2, 0x88, 0xca, 0x56, 0x97, 0x7c, 0x79, 0x2e, 0x5b, 0x28, 0x48, 0x37, 0x68, 0xb3, 0xb8, 0x6a,
	0xa1, 0x20, 0xdd, 0x63, 0x16, 0x0f, 0x57, 0x9c, 0x99, 0x84, 0x79, 0x76, 0x7a, 0xcc, 0x8e, 0x0b,
	0xf8, 0x28, 0x4b, 0xc4, 0x6e, 0x18, 0x96, 0xe6, 0xd5, 0xf8, 0xbe, 0x23, 0x58, 0xb9, 0x94, 0xa0,
	0x41, 0x5a, 0x60, 0xa6, 0x94, 0x73, 0x12, 0xd3, 0x2a, 0x43, 0x9b, 0x43, 0xf0, 0xeb, 0x63, 0xe1,
	0x37, 0xc6, 0xc3, 0x9f, 0x99, 0x04, 0x7f, 0x76, 0x12, 0x7c, 0xe3, 0x37, 0x24, 0x5f, 0x05, 0x83,
	0xf6, 0x12, 0x2e, 0xb8, 0x65, 0x6e, 0xa2, 0xad, 0x39, 0x5f, 0x5b, 0xce, 0x1b, 0x04, 0x58, 0xc9,
	0x78, 0x94, 0x9d, 0xb0, 0x61, 0x94, 0x13, 0x26, 0xef, 0x21, 0x98, 0x4d, 0xd2, 0x26, 0x59, 0x48,
	0xa7, 0x1a, 0xbd, 0x2a, 0x09, 0xdf, 0x81, 0xa5, 0x42, 0x91, 0x1f, 0x48, 0x62, 0x25, 0x2d, 0xb3,
	0xfe, 0xa2, 0x76, 0xee, 0x4b, 0xb1, 0xde, 0x23, 0xb8, 0x79, 0x58, 0x90, 0x4c, 0xec, 0xb6, 0xdb,
	0xac, 0x5b, 0xe6, 0x5d, 0x29, 0x18, 0x3e, 0x84, 0x45, 0x85, 0x35, 0x68, 0x27, 0x69, 0x32, 0xdd,
	0x87, 0xb1, 0xa0, 0x32, 0x8f, 0xcb, 0x44, 0x6c, 0x03, 0xd0, 0x5e, 0x9e, 0x14, 0x44, 0x24, 0x2c,
	0x93, 0xed, 0x35, 0xfc, 0x21, 0x8f, 0xf3, 0xb6, 0x0e, 0xab, 0xbf, 0x36, 0x77, 0x6d, 0xc3, 0x11,
	0x97, 0x85, 0x69, 0x51, 0x0d, 0x87, 0x36, 0x2f, 0x22, 0x54, 0x4e, 0xc7, 0x79, 0x84, 0x8e, 0xd0,
	0x62, 0xfe, 0x19, 0x5a, 0xe6, 0x46, 0x68, 0x79, 0x87, 0xc0, 0x92, 0xb4, 0x1c, 0x1c, 0x1d, 0x8c,
	0xc8, 0xb6, 0x0c, 0x8d, 0x28, 0x89, 0x34, 0x29, 0xe5, 0xf1, 0xfa, 0xe4, 0xfa, 0x50, 0x87, 0xb5,
	0x31, 0x7d, 0xfd, 0x6b, 0xc5, 0x36, 0x60, 0x41, 0x4b, 0x14, 0x94, 0xcc, 0x28, 0xd5, 0x40, 0xbb,
	0x0e, 0xc6, 0x10, 0xf4, 0xb7, 0x84, 0xdb, 0x7b, 0x72, 0xda, 0xb7, 0xd1, 0x59, 0xdf, 0x46, 0xdf,
	0xfa, 0x36, 0x7a, 0x3d, 0xb0, 0x6b, 0x67, 0x03, 0xbb, 0xf6, 0x65, 0x60, 0xd7, 0x9e, 0xee, 0xc4,
	0x89, 0x28, 0x57, 0x61, 0xc8, 0x52, 0x4f, 0x2d, 0xc6, 0x8c, 0x8a, 0x2e, 0x2b, 0x9e, 0x79, 0x17,
	0x5b, 0x94, 0xe4, 0x79, 0xb5, 0x49, 0xc5, 0xcb, 0x9c, 0xf2, 0xa6, 0x21, 0x77, 0xda, 0xce, 0xcf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x0c, 0xed, 0x6e, 0x6a, 0x07, 0x00, 0x00,
}

func (m *FaucetRequestRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FaucetRequestRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FaucetRequestRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFaucet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FaucetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FaucetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FaucetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FaucetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FaucetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FaucetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFaucet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.RawLog) > 0 {
		i -= len(m.RawLog)
		copy(dAtA[i:], m.RawLog)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.RawLog)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Code != 0 {
		i = encodeVarintFaucet(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Txhash) > 0 {
		i -= len(m.Txhash)
		copy(dAtA[i:], m.Txhash)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Txhash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InitAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InitAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InitAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InitAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InitAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InitAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Exists {
		i--
		if m.Exists {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	{
		size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFaucet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RawLog) > 0 {
		i -= len(m.RawLog)
		copy(dAtA[i:], m.RawLog)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.RawLog)))
		i--
		dAtA[i] = 0x22
	}
	if m.Code != 0 {
		i = encodeVarintFaucet(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Txhash) > 0 {
		i -= len(m.Txhash)
		copy(dAtA[i:], m.Txhash)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Txhash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FaucetInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FaucetInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FaucetInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestCount != 0 {
		i = encodeVarintFaucet(dAtA, i, uint64(m.RequestCount))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Balance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFaucet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GrantAllowanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GrantAllowanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GrantAllowanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Expiration != 0 {
		i = encodeVarintFaucet(dAtA, i, uint64(m.Expiration))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.AmountLimit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFaucet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GrantAllowanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GrantAllowanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GrantAllowanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Expiration != 0 {
		i = encodeVarintFaucet(dAtA, i, uint64(m.Expiration))
		i--
		dAtA[i] = 0x40
	}
	{
		size, err := m.AmountLimit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFaucet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.Grantee) > 0 {
		i -= len(m.Grantee)
		copy(dAtA[i:], m.Grantee)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Grantee)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Granter) > 0 {
		i -= len(m.Granter)
		copy(dAtA[i:], m.Granter)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Granter)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RawLog) > 0 {
		i -= len(m.RawLog)
		copy(dAtA[i:], m.RawLog)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.RawLog)))
		i--
		dAtA[i] = 0x22
	}
	if m.Code != 0 {
		i = encodeVarintFaucet(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Txhash) > 0 {
		i -= len(m.Txhash)
		copy(dAtA[i:], m.Txhash)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Txhash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GrantDIDAllowanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GrantDIDAllowanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GrantDIDAllowanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Expiration != 0 {
		i = encodeVarintFaucet(dAtA, i, uint64(m.Expiration))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.AmountLimit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFaucet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GrantDIDAllowanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GrantDIDAllowanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GrantDIDAllowanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Expiration != 0 {
		i = encodeVarintFaucet(dAtA, i, uint64(m.Expiration))
		i--
		dAtA[i] = 0x40
	}
	{
		size, err := m.AmountLimit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFaucet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.GranteeDid) > 0 {
		i -= len(m.GranteeDid)
		copy(dAtA[i:], m.GranteeDid)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.GranteeDid)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Granter) > 0 {
		i -= len(m.Granter)
		copy(dAtA[i:], m.Granter)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Granter)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.RawLog) > 0 {
		i -= len(m.RawLog)
		copy(dAtA[i:], m.RawLog)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.RawLog)))
		i--
		dAtA[i] = 0x22
	}
	if m.Code != 0 {
		i = encodeVarintFaucet(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Txhash) > 0 {
		i -= len(m.Txhash)
		copy(dAtA[i:], m.Txhash)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Txhash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintFaucet(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFaucet(dAtA []byte, offset int, v uint64) int {
	offset -= sovFaucet(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FaucetRequestRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovFaucet(uint64(l))
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	return n
}

func (m *FaucetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	return n
}

func (m *FaucetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Txhash)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	if m.Code != 0 {
		n += 1 + sovFaucet(uint64(m.Code))
	}
	l = len(m.RawLog)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovFaucet(uint64(l))
	return n
}

func (m *InitAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	return n
}

func (m *InitAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = len(m.Txhash)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	if m.Code != 0 {
		n += 1 + sovFaucet(uint64(m.Code))
	}
	l = len(m.RawLog)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovFaucet(uint64(l))
	if m.Exists {
		n += 2
	}
	return n
}

func (m *FaucetInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = m.Balance.Size()
	n += 1 + l + sovFaucet(uint64(l))
	if m.RequestCount != 0 {
		n += 1 + sovFaucet(uint64(m.RequestCount))
	}
	return n
}

func (m *GrantAllowanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = m.AmountLimit.Size()
	n += 1 + l + sovFaucet(uint64(l))
	if m.Expiration != 0 {
		n += 1 + sovFaucet(uint64(m.Expiration))
	}
	return n
}

func (m *GrantAllowanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = len(m.Txhash)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	if m.Code != 0 {
		n += 1 + sovFaucet(uint64(m.Code))
	}
	l = len(m.RawLog)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = len(m.Granter)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = len(m.Grantee)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = m.AmountLimit.Size()
	n += 1 + l + sovFaucet(uint64(l))
	if m.Expiration != 0 {
		n += 1 + sovFaucet(uint64(m.Expiration))
	}
	return n
}

func (m *GrantDIDAllowanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = m.AmountLimit.Size()
	n += 1 + l + sovFaucet(uint64(l))
	if m.Expiration != 0 {
		n += 1 + sovFaucet(uint64(m.Expiration))
	}
	return n
}

func (m *GrantDIDAllowanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = len(m.Txhash)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	if m.Code != 0 {
		n += 1 + sovFaucet(uint64(m.Code))
	}
	l = len(m.RawLog)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = len(m.Granter)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = len(m.GranteeDid)
	if l > 0 {
		n += 1 + l + sovFaucet(uint64(l))
	}
	l = m.AmountLimit.Size()
	n += 1 + l + sovFaucet(uint64(l))
	if m.Expiration != 0 {
		n += 1 + sovFaucet(uint64(m.Expiration))
	}
	return n
}

func sovFaucet(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFaucet(x uint64) (n int) {
	return sovFaucet(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FaucetRequestRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFaucet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FaucetRequestRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FaucetRequestRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFaucet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFaucet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FaucetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFaucet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FaucetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FaucetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFaucet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFaucet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FaucetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFaucet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FaucetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FaucetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txhash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txhash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawLog", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawLog = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFaucet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFaucet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InitAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFaucet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InitAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InitAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFaucet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFaucet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InitAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFaucet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InitAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InitAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txhash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txhash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawLog", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawLog = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exists", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exists = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipFaucet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFaucet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FaucetInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFaucet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FaucetInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FaucetInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestCount", wireType)
			}
			m.RequestCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestCount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFaucet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFaucet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GrantAllowanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFaucet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GrantAllowanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GrantAllowanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			m.Expiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFaucet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFaucet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GrantAllowanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFaucet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GrantAllowanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GrantAllowanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txhash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txhash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawLog", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawLog = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Granter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Granter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Grantee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Grantee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			m.Expiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFaucet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFaucet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GrantDIDAllowanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFaucet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GrantDIDAllowanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GrantDIDAllowanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			m.Expiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFaucet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFaucet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GrantDIDAllowanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFaucet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GrantDIDAllowanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GrantDIDAllowanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txhash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txhash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RawLog", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RawLog = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Granter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Granter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GranteeDid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GranteeDid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFaucet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFaucet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiration", wireType)
			}
			m.Expiration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Expiration |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFaucet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFaucet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFaucet(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFaucet
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFaucet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFaucet
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFaucet
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFaucet
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFaucet        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFaucet          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFaucet = fmt.Errorf("proto: unexpected end of group")
)
