syntax = "proto3";
package sourcehub.hub;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "sourcehub/hub/params.proto";
import "sourcehub/hub/ica_connection.proto";
import "sourcehub/hub/jws_token.proto";

option go_package = "github.com/sourcenetwork/sourcehub/x/hub/types";

// GenesisState defines the hub module's genesis state.
message GenesisState {
  // params defines all the parameters of the module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  // ica_connections defines the list of ICA connections.
  repeated ICAConnection ica_connections = 2 [(gogoproto.nullable) = false];
  // jws_tokens defines the list of JWS token records.
  repeated JWSTokenRecord jws_tokens = 3 [(gogoproto.nullable) = false];
}