syntax = "proto3";
package sourcehub.hub;

import "amino/amino.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/sourcenetwork/sourcehub/x/hub/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "sourcehub/x/hub/Params";
  option (gogoproto.equal) = true;

  // trusted_relay_fee_granters are service accounts whose fee grants authorize
  // workers to relay bearer-authenticated transactions.
  repeated string trusted_relay_fee_granters = 1;
}
